export type CameraCraftReference = { title: string; url: string; source: string; accessed: string };
export type CameraCraftLesson = {
  summary: string;
  theory: { heading: string; body: string }[];
  objectives: string[];
  examples: string[];
  mistakes: string[];
  references: CameraCraftReference[];
};

const accessed = "2026-07-30";
const R = (title: string, url: string, source: string): CameraCraftReference => ({ title, url, source, accessed });
const arriDR = R("Dynamic Range — White Paper", "https://www.arri.com/resource/blob/295460/e10ff8a5b3abf26c33f8754379b57442/2022-09-28-arri-dynamic-range-whitepaper-data.pdf", "ARRI");
const bmManual = R("Blackmagic Cinema Camera Manual", "https://documents.blackmagicdesign.com/UserManuals/BlackmagicCinemaCameraManual.pdf", "Blackmagic Design");
const resolveTraining = R("DaVinci Resolve — official training", "https://www.blackmagicdesign.com/products/davinciresolve/training", "Blackmagic Design");
const zeissDoF = R("Depth of Field and Bokeh — technical article", "https://lenspire.zeiss.com/photo/app/uploads/2022/02/technical-article-depth-of-field-and-bokeh.pdf", "ZEISS");
const zeissCircle = R("Large Image Circle, Universal Usability", "https://lenspire.zeiss.com/cine/en/article/large-image-circle-universal-usability-the-compact-prime-cp-3-and-cinema-zoom-cz-2-lens-families", "ZEISS");
const arriLight = R("Lighting learning resources", "https://www.arri.com/en/learn-help/lighting/lighting-systems", "ARRI");
const djiSupport = R("Ronin support, specifications and operating guidance", "https://www.dji.com/support/product/ronin", "DJI");
const djiShake = R("Solutions to gimbal shaking", "https://repair.dji.com/help/content?customId=01700007640&lang=en&paperDocType=ARTICLE", "DJI");
const kodak = R("The Essential Reference Guide for Filmmakers", "https://www.kodak.com/content/products-brochures/Film/Essential-Reference-Guide-for-Filmmakers.pdf", "Kodak");
const E = (summary: string, theory: CameraCraftLesson["theory"], objectives: string[], examples: string[], mistakes: string[], references: CameraCraftReference[]): CameraCraftLesson => ({ summary, theory, objectives, examples, mistakes, references });

export const cameraCraftKnowledge: Record<string, CameraCraftLesson> = {
  "Image Formation & Sensor Language": E(
    "A camera does not record objects; it records a spatial pattern of light. A lens projects that pattern onto a sensor, whose photosites convert incoming photons into electrical measurements that are sampled, processed, encoded and later interpreted as an image.",
    [
      { heading: "From scene to image plane", body: "Light reflected or emitted by the scene enters the lens. Refraction bends different ray bundles so points at the chosen focus distance converge on the image plane; points away from that plane form blur circles rather than sharp points." },
      { heading: "A photosite is a measurement site", body: "During the exposure each photosite accumulates charge in proportion to the photons it receives, within noise and capacity limits. A sensor therefore begins as a grid of luminance-related samples, not a finished color picture." },
      { heading: "How a color mosaic becomes RGB", body: "Most cinema sensors place red, green or blue filters over different photosites. Debayering estimates a full RGB value at every output pixel from neighboring filtered measurements, so fine repeating detail can challenge the reconstruction and produce moiré or false color." },
      { heading: "Photosites, pixels and resolution", body: "A photosite is physical; a pixel is an image sample. Output dimensions may result from cropping, binning, line-skipping, oversampling or rescaling, so a 4K file label alone does not describe captured detail, aliasing or noise." },
      { heading: "The chain has creative consequences", body: "Sensor size changes the lens and distance choices required for a given framing; full-well capacity influences highlight clipping; read noise influences shadow cleanliness; rolling readout can skew motion. Sensor language is useful when it predicts a visible result rather than acting as specification trivia." },
    ],
    ["Trace an image from scene light through lens, sensor, debayer and encoded file", "Distinguish photosites, pixels, resolution and sensor size", "Connect sensor sampling limits to clipping, noise, aliasing and rolling-shutter artifacts"],
    ["Compare a fine fabric at several recording modes to reveal aliasing", "Frame the same view on two sensor formats by changing focal length, then compare depth and noise under controlled exposure"],
    ["Saying a sensor captures a ready-made RGB image", "Treating pixel count as the sole measure of image quality", "Attributing perspective directly to sensor size instead of the camera position it encourages"],
    [bmManual, arriDR, kodak],
  ),
  "Stops and Exposure Triangle": E(
    "A stop is a ratio: one stop more exposure doubles the light reaching the sensor and one stop less halves it. Aperture, exposure time and scene illumination control photon capture; ISO usually controls gain or interpretation and carries different side effects.",
    [
      { heading: "Stops make unlike controls comparable", body: "Changing from f/4 to f/2.8, from 1/96 to 1/48 second, or doubling illuminance each adds one stop of exposure. The notation lets crews trade controls while tracking the total change." },
      { heading: "Aperture is not just brightness", body: "The f-number is focal length divided by entrance-pupil diameter. Opening the iris admits more light but also changes depth of field, diffraction balance, aberrations and the rendering of out-of-focus highlights." },
      { heading: "Time writes motion", body: "Longer exposure records more light and more movement during each frame; shorter exposure records less light and freezes a smaller slice of motion. Frame rate determines how often those slices are shown, so shutter and frame rate must be judged together." },
      { heading: "ISO is the misleading corner", body: "Raising ISO does not put more photons into the sensor. Depending on the camera it changes analog gain, digital scaling, metadata or a mixture; a brighter monitor image can conceal that underexposed shadows contain a weak signal." },
      { heading: "Expose by priority", body: "Choose frame rate and shutter for motion, aperture for optical intent, and lighting or ND for scene level. Set the camera's exposure index with knowledge of its headroom behavior, then verify important tones on a waveform or false-color scale." },
    ],
    ["Calculate one- and two-stop changes across aperture, shutter and illumination", "Name the non-exposure side effect of every control", "Build an exposure while preserving chosen motion blur and depth of field"],
    ["Hold f/2.8 and 1/48 while adding ND outdoors instead of sacrificing the intended rendering", "Trade one stop of aperture for one stop of light and compare image character at equal exposure"],
    ["Calling ISO captured light", "Changing shutter merely to fix brightness without considering motion", "Memorizing settings without measuring the important subject tones"],
    [bmManual, arriDR, kodak],
  ),
  "Shutter Angle & Motion Cadence": E(
    "Shutter angle expresses exposure duration as a fraction of the frame interval. At 24 fps, 180° is 1/48 second; the choice controls the length of motion trails within each frame and therefore the texture and legibility of movement.",
    [
      { heading: "Angle travels with frame rate", body: "Exposure time equals shutter angle divided by 360 and frame rate. A constant 180° maintains a similar blur proportion when changing from 24 to 48 fps, while a fixed 1/48 second at 48 fps becomes a 360° exposure." },
      { heading: "Blur connects sampled moments", body: "Cinema is a sequence of discrete samples. Motion blur softens the displacement between them; too little can make pans and action stutter, while too much can erase texture and make tracking or compression less reliable." },
      { heading: "Cadence includes display and camera motion", body: "Judder is influenced by frame rate, shutter, subject speed, viewing size and pan rate. A perfectly exposed 24 fps shot can still be unpleasant if high-contrast edges cross a large screen too quickly." },
      { heading: "Creative deviations have a signature", body: "A narrow angle produces crisp, urgent, staccato motion; a wide angle produces streaked, dreamlike or disoriented motion. The effect is strongest on fast movement and should be chosen for narrative meaning, not as a vague cinematic preset." },
      { heading: "Artificial light imposes constraints", body: "Mains-powered and PWM-dimmed sources can pulse out of phase with the exposure window, creating bands or brightness beats. Test the actual source and use flicker-free rates or shutter values rather than assuming 180° is always safe." },
    ],
    ["Convert between frame rate, shutter angle and exposure time", "Diagnose judder, excessive blur and lighting flicker separately", "Choose a shutter treatment that describes the intended movement"],
    ["Shoot the same running action at 45°, 180° and 360°", "Pan past vertical window frames at progressively slower rates and assess cadence on the target display"],
    ["Using 1/50 at every frame rate", "Calling every choppy pan a shutter problem", "Discovering LED flicker only after leaving the location"],
    [bmManual, kodak],
  ),
  "ISO, Gain & Noise": E(
    "ISO and gain determine how the camera maps or amplifies the sensor signal; they do not replace exposure. Noise becomes visible when the desired signal contains too few photons, when electronics add uncertainty, or when later amplification makes those uncertainties conspicuous.",
    [
      { heading: "Signal-to-noise begins at capture", body: "Photon arrival varies statistically: a stronger exposure has a better photon signal-to-noise ratio. Read noise and fixed-pattern noise are added by sensor electronics, while compression can add structured artifacts later." },
      { heading: "Exposure index versus physical sensitivity", body: "Cinema cameras may retain the same underlying capture while EI changes monitoring and metadata, reallocating apparent stops around middle gray. Other cameras switch analog circuits at specific ISOs. Only camera-specific tests reveal which behavior applies." },
      { heading: "Why underexposure hurts", body: "If a face is recorded several stops low and lifted in post, both its weak signal and the noise floor are enlarged. Protecting highlights by starving every midtone is not the same as deliberately placing highlights within measured headroom." },
      { heading: "Noise has patterns", body: "Fine random luma grain, colored chroma blotches, horizontal banding, fixed pixels and codec macroblocking have different causes. Zooming into a still frame is insufficient; evaluate noise at playback speed after the intended transform." },
      { heading: "A repeatable camera test", body: "Light a gray card, face, deep texture and bright practical. Record a bracket at controlled settings, normalize consistently, then compare highlight retention, shadow color, motion and required post lift—not just monitor brightness on set." },
    ],
    ["Explain why raising ISO is not equivalent to adding light", "Identify major noise families by appearance", "Design an exposure-index bracket that keeps scene and post treatment controlled"],
    ["Compare ISO 400 underexposed two stops and lifted with ISO 400 correctly exposed", "Test both sides of a dual-native-gain switch while holding captured exposure constant"],
    ["Judging noise from the log image before normalization", "Assuming lower ISO always gives cleaner results", "Applying denoise before understanding whether the defect is banding, compression or weak exposure"],
    [arriDR, bmManual],
  ),
  "Dynamic Range & Highlight Strategy": E(
    "Dynamic range is the span between a camera's usable noise floor and saturation. Highlight strategy means deciding which bright values must retain texture, measuring where they land, and allowing unimportant sources to clip only by conscious choice.",
    [
      { heading: "Range is bounded at both ends", body: "At the top, a photosite reaches capacity and additional photons cannot be distinguished; at the bottom, the scene signal becomes indistinguishable from noise. Manufacturer stop counts depend on the usability criterion and are not interchangeable without method." },
      { heading: "Middle gray locates, not creates, latitude", body: "Placing an 18% card at the recommended signal level gives a known reference. Exposure index and log encoding determine how much encoded or displayed room appears above it, but scene lighting and captured photons determine what information exists." },
      { heading: "Highlights differ in importance", body: "A clipped sun or specular sparkle may look natural; clipped skin, cloud texture or a white costume can destroy the shot's subject. Rank highlights by story value before deciding what to sacrifice." },
      { heading: "Log preserves code allocation, not infinite detail", body: "A log curve compresses scene values into a recordable signal so available bits are used efficiently. It cannot restore a saturated photosite, and an output LUT can clip values that still exist upstream." },
      { heading: "Shape the scene, not only the camera", body: "Reduce a window, add fill, move the subject, change time of day, dim practicals or flag reflections. Dynamic-range problems are often contrast-design problems best solved before recording." },
    ],
    ["Distinguish sensor saturation, display clipping and LUT clipping", "Create a highlight priority list for a shot", "Use exposure and lighting controls to fit essential values into the camera's usable range"],
    ["Expose a face beside a window and compare clipping the window with lowering its level", "Disable an output LUT to check whether apparently clipped data survives in log"],
    ["Protecting every specular at the cost of the subject", "Quoting a stop count without its test criterion", "Assuming flat-looking log footage cannot be clipped"],
    [arriDR, bmManual],
  ),
  "White Balance, Tint & Color Temperature": E(
    "White balance tells the imaging pipeline how to interpret the relative red, green and blue response under an illuminant. Color temperature describes the warm–cool axis of near-blackbody light; tint provides a separate green–magenta correction for sources that do not lie on that axis.",
    [
      { heading: "Kelvin describes the source first", body: "Lower-temperature blackbody sources appear warmer and higher-temperature sources cooler. The camera correction works oppositely: selecting a higher Kelvin value adds a warmer compensation because it assumes a bluer illuminant." },
      { heading: "Tint is not Kelvin", body: "Fluorescent, discharge and LED spectra may be greener or more magenta than the blackbody/daylight locus. Moving Kelvin alone cannot neutralize that perpendicular error; tint or source correction is required." },
      { heading: "Neutral reference versus creative bias", body: "A gray card under the subject light establishes a reproducible neutral interpretation. You may then retain sunset warmth or cool moonlight deliberately; neutralizing every source erases relationships that belong to the scene." },
      { heading: "Mixed spectra can resist global repair", body: "Two sources can share a nominal CCT while rendering skin and fabric differently because their spectral power distributions differ. A single white-balance setting cannot make missing wavelengths reappear or reconcile severe metameric mismatch." },
      { heading: "Raw flexibility still has limits", body: "Raw metadata often permits later WB changes before demosaic, but channel clipping and weak channel exposure remain. Correcting an extremely blue image can amplify a starved red channel and reveal noise even when the file is raw." },
    ],
    ["Separate CCT correction from green–magenta tint", "Set a reproducible neutral balance and then articulate a creative deviation", "Recognize when mixed-source spectral quality cannot be fixed with one global control"],
    ["Record skin under daylight and a poor LED at the same meter CCT", "White-balance on a gray card, then compare intentional 4300 K and 6500 K interpretations"],
    ["Believing high camera Kelvin makes the source cooler", "Using a white painted wall as a guaranteed neutral target", "Treating raw white balance as permission to ignore channel clipping"],
    [bmManual, resolveTraining, kodak],
  ),
  "Monitoring: Histograms, Waveforms & False Color": E(
    "Exposure tools answer different questions. A histogram counts values but loses their location; a waveform preserves horizontal position; false color converts defined signal ranges into fast visual zones whose legend must be learned for the particular device.",
    [
      { heading: "What a histogram forgets", body: "The graph shows how many pixels are dark, mid or bright. It cannot tell whether a small clipped cluster is a face, lamp or harmless reflection, and its shape has no universal ideal." },
      { heading: "Waveform maps the frame", body: "Left-to-right position corresponds to the image, while height shows signal level. This makes it possible to compare two faces, trace a gradient, locate clipping and inspect whether a background is even." },
      { heading: "False color is a labeled measurement", body: "Colors are assigned to manufacturer-defined IRE or exposure ranges. Pink on one monitor may not mean the same thing on another, and the reading may occur before or after a LUT; always display the legend and identify the monitored signal path." },
      { heading: "Log and display-referred values differ", body: "A camera log signal places gray and white at camera-specific code values. A Rec.709 transform expands these into display contrast. Exposure targets are valid only when they refer to the same signal location in the pipeline." },
      { heading: "Use tools with the picture", body: "Scopes verify placement; they do not decide which object matters. First name the subject and highlight policy, then use the correct tool to confirm it while watching for channel clipping, noise and the intended viewing transform." },
    ],
    ["Select the correct exposure tool for location, distribution or rapid zoning", "Explain where the LUT sits in the monitoring chain", "Measure a face and a highlight without relying on screen brightness"],
    ["Place two gray cards at opposite sides of frame and identify each waveform trace", "Make a small practical clip and observe how little warning it creates in the histogram"],
    ["Trying to create a bell-shaped histogram", "Copying false-color meanings between brands", "Exposing log by eye on an uncalibrated bright monitor"],
    [bmManual, resolveTraining],
  ),
  "Exposure Integration Project": E(
    "This project turns isolated exposure facts into a defensible on-set method: define motion and depth, measure critical tones, control scene contrast, record a bracket, and carry the selected negative through a consistent transform and review.",
    [
      { heading: "Write the visual constraint", body: "Specify frame rate, motion-blur character, desired depth of field, critical face or object, and highlights that must hold. These decisions remove arbitrary freedom from the exposure setup." },
      { heading: "Build a measurable test scene", body: "Include skin or a textured midtone, deep colored fabric, neutral reference, saturated color, diffuse white and a bright specular. Keep lighting and camera position fixed so each exposure difference has meaning." },
      { heading: "Bracket one variable at a time", body: "Record a reference and measured stop offsets. If testing EI, preserve lens exposure; if testing aperture character, compensate with light or ND. Slate every take with settings so memory cannot rewrite the result." },
      { heading: "Normalize consistently", body: "Apply the same raw decode, color-space transform and output conditions before comparing. Judge retained texture, color separation, noise in motion and recovery cost, not the deceptive flatness of log thumbnails." },
      { heading: "Convert findings into a field rule", body: "Document a preferred starting EI, face placement, highlight warning, acceptable underexposure boundary and monitoring configuration for this camera. State the scene conditions under which the rule stops applying." },
    ],
    ["Run a controlled exposure latitude test", "Separate capture differences from post-transform differences", "Produce a camera-specific exposure card supported by evidence"],
    ["Test a window-lit portrait with controllable fill", "Compare a clean reference to one-stop over and under versions in the finished display transform"],
    ["Changing aperture, shutter and ISO together", "Comparing clips through different automatic adjustments", "Declaring a universal best ISO from one lighting condition"],
    [arriDR, bmManual, resolveTraining],
  ),
  "Focal Length & Field of View": E("Focal length describes an optical property; together with sensor dimensions it determines angle of view. It changes magnification from a fixed camera position, while the position—not the focal-length number—sets perspective relationships.", [
    { heading: "Focal length is physical", body: "For a lens focused near infinity, focal length relates the optical system to the image plane. A 25 mm remains a 25 mm on every mount; only the recorded crop and resulting field of view change with sensor area." },
    { heading: "Field of view needs two dimensions", body: "Horizontal, vertical and diagonal angles differ with aspect ratio. A lens described as wide on Super 35 may appear normal on a smaller sensor because the smaller image area samples less of its image circle." },
    { heading: "Framing from a fixed mark", body: "Changing to a longer lens without moving enlarges every object by the same projection geometry and narrows the visible scene. Cropping a wider-lens image from that same mark can match perspective, though resolution, depth of field and optical rendering may differ." },
    { heading: "Lens choice changes operating distance", body: "In practice filmmakers move to restore subject size after changing focal length. That move changes near–far size relationships, eyeline intimacy and parallax, which is why focal length appears to alter perspective." },
    { heading: "Build a field-of-view kit", body: "Record reference frames from fixed floor marks with every available lens and note sensor mode. These images are more reliable for planning than full-frame-equivalent labels detached from the actual camera." },
  ], ["Predict field of view from focal length and sensor format", "Separate magnification from perspective", "Choose a lens after choosing the camera's spatial relationship"], ["Compare 25, 50 and 100 mm from one locked position", "Match a medium shot with wide and long lenses by moving, then compare the background"], ["Calling a lens itself a crop lens", "Comparing focal lengths without naming sensor mode", "Choosing focal length before deciding where the audience should stand"], [zeissCircle, zeissDoF]),
  "Perspective & Camera Distance": E("Perspective is the pattern of relative size and occlusion produced by a viewpoint. Moving the camera changes that geometry; changing focal length from the same point only reframes or magnifies it.", [
    { heading: "Viewpoint creates size ratios", body: "A nearby nose is proportionally much closer than the ears, so it projects larger; from farther away their distance difference is a smaller percentage. This is the source of the familiar close wide-lens and distant long-lens portrait renderings." },
    { heading: "Foreground and background", body: "Moving closer expands foreground relative to background and increases parallax. Moving back compresses their apparent size difference and reduces parallax, even before a lens is chosen to restore framing." },
    { heading: "Occlusion carries spatial meaning", body: "A small lateral move can reveal or hide objects and change which planes overlap. Lens zooming cannot reproduce those changed sight lines because it does not move the viewpoint." },
    { heading: "Faces reveal careless distance", body: "Very close positions can exaggerate central features; distant positions flatten facial depth and may feel observational. Choose distance for emotional and anatomical rendering, then frame with focal length." },
    { heading: "Prove it with overlays", body: "Shoot two focal lengths from the same tripod and crop the wider shot to match: geometry aligns. Then match framing by moving and overlay again: background scale and spatial relationships diverge." },
  ], ["Identify viewpoint as the cause of perspective", "Use distance to control facial and environmental relationships", "Demonstrate the principle with a controlled camera test"], ["Move around foreground railings to design reveals", "Create intimate and detached close-ups at different distances"], ["Saying telephoto lenses compress space by themselves", "Matching subject size while forgetting the changed background", "Backing into unsafe spaces without marking and checking the path"], [zeissCircle, kodak]),
  "Aperture, T-Stops & Transmission": E("An f-stop is a geometric ratio; a T-stop describes measured light transmission. Both guide exposure, while iris shape and lens design also change depth of field, diffraction, aberrations, vignetting and out-of-focus rendering.", [
    { heading: "The f-number", body: "f/N equals focal length divided by entrance-pupil diameter. Each full-stop sequence changes pupil area by about two, which explains the √2 progression: 1.4, 2, 2.8, 4 and onward." },
    { heading: "Why T-stops exist", body: "Glass, coatings and internal surfaces absorb or reflect some light. A T2 lens is calibrated to transmit the exposure expected at T2, helping multiple cinema lenses match more closely than their geometric f-numbers alone." },
    { heading: "Iris changes rendering", body: "Opening reduces depth of field and may reveal spherical aberration, softness or vignetting; closing usually improves uniformity until diffraction spreads detail. The optimal stop is a visual and practical compromise, not always the widest available." },
    { heading: "Ramp and breathing", body: "Some zooms lose transmission as focal length increases, and some lenses change angle of view during focus. Mark these behaviors during prep because neither is communicated by the headline maximum aperture." },
    { heading: "Control exposure without surrendering intent", body: "If T2 is chosen for separation and character, use ND, lighting or shutter-compatible scene control to retain it. Treat aperture as an optical decision before using it as an emergency brightness knob." },
  ], ["Calculate f-number relationships", "Explain the practical distinction between f- and T-stops", "Test a lens across its aperture range for usable character"], ["Match two cinema primes at T2.8 and inspect waveform consistency", "Shoot point lights wide open and stopped down to study iris shape"], ["Assuming identical f-stops transmit identically", "Always shooting wide open because it sounds cinematic", "Ignoring exposure ramping during a zoom"], [zeissDoF, zeissCircle, kodak]),
  "Depth of Field & Circle of Confusion": E("Depth of field is the range rendered acceptably sharp under a chosen viewing condition. It is not a hard physical wall: it depends on aperture, magnification, focus distance, focal length/format choices and the circle-of-confusion criterion.", [
    { heading: "Only one plane is exact", body: "An ideal thin lens focuses one object plane onto the sensor plane. Points before or behind it become discs; depth of field labels discs below an agreed diameter as acceptably sharp." },
    { heading: "The criterion includes exhibition", body: "A circle acceptable on a phone may be obvious on a cinema screen. Sensor size alone does not dictate the criterion; output enlargement, resolution, viewing distance and artistic tolerance all matter." },
    { heading: "Magnification is central", body: "Closer focus and larger subject magnification reduce depth of field. Format comparisons become meaningful only after stating whether framing, position, focal length and aperture are held or changed." },
    { heading: "Near and far are unequal", body: "The depth around focus is not always one-third/two-thirds. Distribution varies with distance and approaches the hyperfocal case, where the far limit reaches infinity." },
    { heading: "Use calculators as starting points", body: "Tables assume a circle criterion and often perfect lenses. Confirm critical focus on the actual sensor, lens, stop and target display, particularly for high-resolution close-ups." },
  ], ["Define circle of confusion and acceptable sharpness", "Predict how aperture, focus distance and magnification affect depth", "Challenge format claims by identifying controlled variables"], ["Hold framing and compare T2 with T5.6", "Rack through near, subject and background marks to see blur growth rather than a sharp boundary"], ["Repeating the one-third/two-thirds myth as a law", "Equating shallow depth with emotional depth", "Using a phone preview to approve theatrical focus"], [zeissDoF, zeissCircle]),
  "Focus Methods & Pulling": E("Focus pulling is timed storytelling: the focus plane must arrive on the intended subject with the performance while avoiding distracting search. Reliable work combines measurement, marks, rehearsal, optical knowledge and visual judgment.", [
    { heading: "Establish trustworthy marks", body: "Measure from the camera's sensor-plane mark to the subject, not from the matte box. Check lens witness marks because still lenses and adapted optics may be inaccurate or have a short focus throw." },
    { heading: "Map action, not only distances", body: "A floor mark states where an actor should land, but the eyes can lean forward and the camera may move. Rehearse the actual body and camera path and note moments where subject speed changes." },
    { heading: "Focus is an attention transition", body: "A rack can reveal information, transfer allegiance or create anticipation. Its start, duration and landing should match the dramatic beat rather than merely react after an object moves." },
    { heading: "Depth is a working allowance", body: "Stopping down, widening or increasing distance can make a demanding move robust, but each changes the image. Choose the allowable miss and design the optics with the director and cinematographer." },
    { heading: "Monitoring and assist tools", body: "Peaking detects contrast and can be fooled by noise or textured edges; magnification loses the full composition; autofocus may choose the wrong face. Use aids as evidence alongside calibrated monitors and rehearsed marks." },
  ], ["Create and verify measured focus marks", "Time a rack to a story beat", "Choose optical changes that make a pull achievable"], ["Pull from foreground evidence to a listening face", "Rehearse an actor approaching camera at constant and changing speeds"], ["Measuring from the lens front", "Watching only peaking instead of the subject's eyes", "Beginning every rack only after dialogue names the new object"], [bmManual, zeissDoF]),
  "Lens Character, Aberrations & Contrast": E("Lens character is the repeatable way an optical design renders resolution, contrast, flare, distortion, color and blur across frame, distance and aperture. It should be tested as behavior, not reduced to vintage-versus-clinical adjectives.", [
    { heading: "Resolution and contrast are coupled", body: "A lens can resolve fine lines at low contrast or fewer lines with strong local contrast. Perceived crispness depends on modulation at several spatial frequencies, processing and display—not one sharpness number." },
    { heading: "Aberrations have locations", body: "Spherical aberration affects focus and glow, coma distorts off-axis points, astigmatism separates orientations, field curvature bends the best-focus surface, and chromatic aberration separates wavelengths. Their strength changes with aperture and field position." },
    { heading: "Flare is a source interaction", body: "Ghosts arise from reflections between optical surfaces; veiling glare lowers contrast across larger areas. Source angle, coating, filter stack and matte-box control determine whether flare becomes expressive or merely obscures the subject." },
    { heading: "Distortion and breathing affect sequence continuity", body: "Barrel or pincushion distortion changes geometry, while focus breathing changes framing during a pull. Mixing lenses with visibly different behavior can make cuts pulse even when focal lengths nominally match." },
    { heading: "Test faces, points and movement", body: "Use skin, backlight, straight architecture, point sources, focus racks and edge detail at working stops. Grade every lens consistently so a contrast transform is not mistaken for optical character." },
  ], ["Name common aberrations by visible behavior", "Design a comparative lens-character test", "Choose character that supports a sequence rather than an isolated frame"], ["Sweep a point light across the frame to map flare", "Rack focus past a face and gridded background to reveal breathing and field curvature"], ["Calling all softness vintage", "Testing charts only at infinity", "Adding diffusion before learning the lens's own veiling behavior"], [zeissCircle, zeissDoF]),
  "Filters, ND, IR & Polarization": E("Camera filters selectively alter light before capture. Neutral density controls quantity, IR-cut filters manage invisible contamination, and polarizers manage polarized reflections and sky—but each can introduce color, reflections or spatial unevenness.", [
    { heading: "ND protects chosen optics and motion", body: "ND reduces light so aperture and shutter can remain at their creative settings. Density 0.3 equals one stop, 0.6 two stops and so on; variable ND combines polarizers and can produce color shifts or an X pattern at extremes." },
    { heading: "Infrared becomes visible under heavy ND", body: "Some ND attenuates visible light more strongly than near infrared. Fabrics and blacks can turn brown or magenta because the sensor still receives IR; matched IRND or an appropriate hot mirror controls the imbalance." },
    { heading: "Polarization depends on angle", body: "A linear or circular polarizer can reduce non-metallic reflections and deepen sky roughly 90° from the sun. On wide views the sky angle varies across frame, producing uneven dark bands." },
    { heading: "The filter stack is an optical system", body: "Multiple trays add reflective surfaces, can vignette wide lenses and make ghosts more complex. Rear and clip-in filters sit in different ray geometry and may affect focus or compatibility." },
    { heading: "Rotate while watching the subject", body: "Maximum reflection removal is not automatically best: glass may need to remain visible and skin can lose life. Set polarization for narrative readability, then verify exposure because the filter itself costs light." },
  ], ["Convert optical density to stops", "Recognize IR contamination and polarizer unevenness", "Select and test a minimal filter stack"], ["Compare black synthetic fabric through regular ND and IRND", "Rotate a polarizer on a car window while preserving enough reflection to read the glass"], ["Stacking filters without checking flare", "Using variable ND at its mechanical extreme", "Assuming all black fabrics react equally to IR"], [bmManual, kodak]),
  "Lens Language Chapter Boss": E("The lens-language assignment proves that camera position, focal length, focus, aperture and filtration are coordinated narrative choices. The result must communicate a shift in relationship or knowledge without depending on dialogue to explain it.", [
    { heading: "Define the spatial argument", body: "Write how near–far scale, inclusion of environment and viewer distance should change across the scene. Place camera marks before selecting focal lengths." },
    { heading: "Build a coherent lens set", body: "Test available lenses for field of view, close focus, breathing, flare, contrast and transmission. Choose a small set whose differences are motivated and whose unwanted mismatches can be controlled." },
    { heading: "Design focus as syntax", body: "List every intended focus transfer with its story trigger and landing. Decide when deep focus lets the viewer choose and when shallow focus withholds competing information." },
    { heading: "Protect the aperture strategy", body: "Calculate lighting and ND needs for the chosen stops. Do not let exterior brightness or a weak interior force an accidental change in depth and character halfway through the sequence." },
    { heading: "Review cuts, not beauty frames", body: "Screen the assembled sequence and watch background scale, eyeline, distortion and focus energy across edits. Defend each lens decision by the information or emotion it changes." },
  ], ["Plan a sequence from viewpoint before focal length", "Integrate focus and aperture with blocking", "Evaluate lens continuity and expressive contrast in an edit"], ["Move from detached long-lens observation to close wide-lens confrontation", "Hold deep focus until a secret is noticed, then transfer attention with a rack"], ["Building a lens demo reel instead of a scene", "Changing focal length on every cut without spatial purpose", "Submitting settings without explaining their visible consequences"], [zeissCircle, zeissDoF, kodak]),
  "Frame, Aspect Ratio & Negative Space": E("The frame is an active boundary: it includes, excludes and gives every object a relationship to an edge. Aspect ratio changes the available geometry, while negative space can create direction, isolation, anticipation or room for movement and text.", [
    { heading: "Edges create pressure", body: "Objects near an edge can feel constrained, unstable or about to leave; objects with generous space can feel calm or exposed. Cropping a body at an awkward joint creates a different tension from a deliberate close fragment." },
    { heading: "Ratio reorganizes relationships", body: "A wide ratio supports lateral separation and group staging; a taller ratio gives vertical architecture and bodies more influence. Ratio does not supply meaning automatically—it changes the compositional problems available." },
    { heading: "Negative space is still information", body: "An apparently empty region may carry gaze direction, off-screen threat, environmental scale, graphic calm or future action. Its tone and texture determine visual weight even without an object." },
    { heading: "Compose for the actual extraction", body: "Open-gate capture may feed several deliverables. Mark protected areas and decide whether one master composition can survive them or whether separate framing passes are required." },
    { heading: "Off-screen space lives through sound and gaze", body: "A look, movement or sound activates territory beyond the edge. Consistent cues allow the audience to imagine a larger world; contradictory cues make the boundary feel arbitrary." },
  ], ["Use frame edges deliberately", "Explain how an aspect ratio changes staging options", "Activate negative and off-screen space with gaze, sound and movement"], ["Place a character against one edge while footsteps occupy the empty side", "Recompose the same two-person scene for 1.33, 1.85 and 2.39"], ["Treating empty space as wasted", "Centering every subject regardless of dramatic pressure", "Cropping later without checking eyelines and body joints"], [kodak, resolveTraining]),
  "Balance, Weight & Visual Hierarchy": E("Visual balance is the distribution of perceptual weight, not mandatory symmetry. Hierarchy determines what the viewer notices first and next through contrast in tone, color, size, sharpness, position, motion and meaning.", [
    { heading: "Weight is contextual", body: "A small bright face can outweigh a large dark wall; a familiar symbol can outweigh an abstract texture. Weight depends on contrast against its surroundings and the viewer's task in the scene." },
    { heading: "Asymmetry can be stable", body: "One large quiet mass may balance several small active elements. The goal is a legible force relationship, which may intentionally lean, isolate or threaten rather than settle." },
    { heading: "Contrast makes hierarchy", body: "The brightest, sharpest, most saturated or fastest element often attracts attention, but semantic importance—especially eyes and faces—can override simple graphic contrast." },
    { heading: "Hierarchy changes in time", body: "An actor enters, a practical switches off or focus moves, and the frame's weight reorganizes. A moving-image composition must guide successive discoveries, not merely look balanced in a still." },
    { heading: "Competing cues create confusion", body: "If lighting says face, motion says window and focus says prop, attention fragments. Rank the story information and align enough cues to make the desired reading probable without making it mechanical." },
  ], ["Identify sources of visual weight", "Construct intentional asymmetric balance", "Design first, second and third points of attention"], ["Balance a large dim foreground against a small bright face", "Shift hierarchy within one shot using blocking and a practical dim"], ["Using rule-of-thirds intersections as hierarchy", "Making every important element equally bright", "Judging only the opening frame of a moving shot"], [kodak, arriLight]),
  "Lines, Shapes, Layers & Depth": E("Lines organize eye travel; shapes create graphic identity; overlapping layers and atmospheric cues build depth on a flat screen. Their value lies in directing story attention and revealing spatial relationships, not decorating a frame.", [
    { heading: "Lines imply force", body: "Horizontals tend toward stability, verticals toward stature, diagonals toward energy, but context controls the reading. Architectural and gaze lines can lead toward the subject or deliberately divert attention." },
    { heading: "Shape supports recognition", body: "Silhouette and grouped masses are read before fine detail. Clear separation between shapes helps action read; merging similar tones can conceal or fuse characters intentionally." },
    { heading: "Overlap proves depth", body: "When one object occludes another, their order becomes unambiguous. Foreground elements also establish parallax during a move, making depth stronger than lens blur alone." },
    { heading: "Tonal and color perspective", body: "Distant planes often lose contrast and saturation through atmosphere, while warm–cool and light–dark separation can distinguish layers. Lighting can exaggerate or invert these cues." },
    { heading: "Depth must remain navigable", body: "Foreground, subject and background each need a job. Random clutter adds planes but can destroy hierarchy; simplify until every layer contributes scale, concealment, context or movement." },
  ], ["Use line direction to guide attention", "Create readable silhouettes and overlaps", "Build foreground, midground and background with distinct narrative roles"], ["Frame through a doorway to create a foreground threshold", "Stage three characters at staggered depths and reveal alliances by overlap"], ["Tilting every shot for energy", "Equating blurry background with dimensional composition", "Adding foreground objects that cover performance without purpose"], [kodak, arriLight]),
  "Headroom, Look Room & Eyelines": E("Headroom and look room are relational spaces that help bodies and gazes continue beyond the frame. Eyelines become spatial evidence across shots; small errors in height or angle can make characters seem to look past one another.", [
    { heading: "Headroom follows scale", body: "A wide shot can tolerate environmental space above a figure; a close-up usually needs less. The critical relationship is the eyes to the upper edge, not a fixed distance above the skull." },
    { heading: "Look room anticipates attention", body: "Space in front of a gaze gives the looked-at subject conceptual territory. Removing it creates pressure, concealment or obstruction, which may be expressive if controlled." },
    { heading: "Eyelines encode camera geometry", body: "The off-screen partner's mark, lens height and camera distance from the axis determine gaze angle. Matching only left-versus-right is insufficient when vertical angle or closeness to lens differs." },
    { heading: "Lens proximity changes intimacy", body: "A partner standing near the lens produces a near-camera gaze that feels connected; farther off-axis creates profile and separation. Dirty over-shoulders provide additional spatial confirmation." },
    { heading: "Monitor performance drift", body: "Actors naturally shift attention between eyes and may lean between takes. Give a precise mark when intercut geometry matters, while preserving natural performance and intentional exceptions." },
  ], ["Adjust headroom by shot scale", "Design look room for comfort or pressure", "Match reciprocal eyelines using height and axis distance"], ["Shoot paired singles with the off-screen actor at two distances from lens", "Break look room when a character feels trapped by an unseen observer"], ["Applying identical headroom to every scale", "Matching only gaze direction", "Putting the eyeline mark on the matte box without testing the resulting angle"], [kodak, bmManual]),
  "Blocking for the Camera": E("Blocking arranges performers, camera and environment over time so dramatic relationships become visible. Strong blocking emerges from intention and change; camera placement then makes those changes legible without forcing actors into lifeless marks.", [
    { heading: "Begin with objectives", body: "Ask who wants what, where power shifts and what action changes the encounter. Movement motivated by those beats feels causal; movement added merely to animate the frame feels ornamental." },
    { heading: "Stage relationships in depth", body: "Distance, height, overlap and orientation externalize intimacy, status and exclusion. A character crossing into another's plane can be more meaningful than a close-up cut announcing the same shift." },
    { heading: "The camera owns a viewpoint", body: "Choose what the audience should know and whose experience organizes the scene. A camera position can reveal a lie, withhold a reaction or make one body dominate another." },
    { heading: "Marks are repeatability tools", body: "Use marks for focus, light and continuity, but rehearse the path between them. Adjust marks to the actor's natural action rather than demanding an arbitrary geometric diagram." },
    { heading: "Coverage should grow from staging", body: "Master, singles and inserts are not a shopping list. Select angles that preserve the scene's spatial argument and capture genuine changes in behavior, then ensure entrances, exits and props can cut." },
  ], ["Translate dramatic beats into spatial changes", "Coordinate blocking with focus and light", "Choose coverage that preserves the scene's viewpoint"], ["Move a passive character from background to shared plane at a decision", "Let an actor motivate a reveal by crossing an occluding foreground"], ["Moving actors without a beat", "Designing camera positions before watching a rehearsal", "Forcing exact marks while losing truthful timing"], [kodak, arriLight]),
  "Screen Direction & Spatial Continuity": E("Screen direction is the apparent left–right orientation of looks and movement. Maintaining or deliberately resetting an axis helps viewers preserve a mental map; breaking it without evidence can reverse relationships and make action unreadable.", [
    { heading: "Establish an axis of action", body: "A line between interacting subjects or along a travel path divides likely camera positions. Staying on one side usually preserves reciprocal gazes and direction across cuts." },
    { heading: "The 180-degree system is a tool", body: "It serves clarity, not obedience. A crossing camera move, neutral-on-axis view, new establishing shot or visible turn can reorient the audience before shots adopt the opposite direction." },
    { heading: "Entrances and exits are vectors", body: "A subject exiting frame right normally continues into the next shot from frame left when travel continues. Re-entering from the same edge can imply reversal unless geography or action explains it." },
    { heading: "Match action phase and energy", body: "A cut during movement hides spatial change when direction, body phase and momentum connect. Matching the prop but changing movement phase creates a perceptual bump." },
    { heading: "Break direction for meaning", body: "A sudden reversal can mark disorientation, betrayal or a new power structure. Establish the prior map strongly enough that the break reads as intention rather than coverage failure." },
  ], ["Draw and apply an axis diagram", "Preserve travel vectors over cuts", "Reorient or break screen direction with visible motivation"], ["Cross the line during a dolly that visibly passes the axis", "Reverse an established chase direction at the moment the pursuer becomes pursued"], ["Treating the axis as a fixed line independent of blocking", "Cutting between opposite directions without a reset", "Matching only body position instead of motion phase"], [kodak, resolveTraining]),
  "Composition Across a Sequence": E("Sequence composition designs relationships between frames: scale, angle, direction, tonal weight and graphic shape should progress with the scene. Continuity gives orientation; controlled contrast makes a cut or beat matter.", [
    { heading: "Frames create expectations", body: "An establishing view teaches geography and visual rules. Later shots may rely on that knowledge, revise it or reveal that the initial frame withheld something." },
    { heading: "Vary scale by information", body: "A close-up is powerful when detail or interior response becomes newly important. Alternating wide and close mechanically can flatten emphasis because every beat receives the same grammar." },
    { heading: "Graphic relations affect cuts", body: "Matching dominant shapes, eye position or movement can make a cut fluid; opposing them can create rupture. Both choices should support the narrative transition." },
    { heading: "Track visual intensity", body: "Contrast, saturation, movement, lens proximity and frame density can rise or fall across a passage. Plotting them reveals whether the visual arc anticipates, supports or fights the dramatic arc." },
    { heading: "Edit the storyboard", body: "Place thumbnails in order and remove dialogue. If attention, geography and shifts in status remain readable, composition is carrying narrative rather than relying on explanation." },
  ], ["Plan shot scale by information change", "Use graphic matches and contrasts deliberately", "Chart visual intensity over a sequence"], ["Move from shared two-shot to isolated singles as trust collapses", "Match a circular prop to a distant sun across a time jump"], ["Composing every shot as an unrelated poster", "Using a close-up for every line", "Maintaining continuity so strictly that no visual change marks the climax"], [resolveTraining, kodak]),
  "Visual Grammar Chapter Boss": E("This assignment asks you to tell a clear dramatic turn through framing, blocking and sequence design. The audience should understand attention, geography and changing relationships even with dialogue muted.", [
    { heading: "Write visual rules", body: "Define aspect ratio, dominant spatial motif, baseline shot scale, screen direction and the condition that permits each rule to change." },
    { heading: "Diagram beats and geography", body: "Map positions, movement vectors, eyelines and the axis for every beat. Identify exactly when the audience learns each spatial fact." },
    { heading: "Build hierarchy into staging", body: "For each setup, name the first and second attention targets and how the frame changes. Use light, focus and movement to support rather than contradict that hierarchy." },
    { heading: "Design the meaningful exception", body: "Reserve a composition, axis crossing, centered frame or scale change for the pivotal beat. A visual exception works only when the prior rule is perceptible." },
    { heading: "Test silently", body: "Screen the cut without dialogue and ask viewers to describe geography, allegiance and the turning point. Revise the specific cue that failed instead of adding explanatory coverage everywhere." },
  ], ["Create a coherent visual-rule set", "Execute readable blocking and continuity", "Use a controlled compositional break to express a dramatic turn"], ["A two-person negotiation that moves from balanced profile to one-sided depth", "A silent search whose negative space becomes occupied at the reveal"], ["Making every frame unusual", "Breaking the axis before establishing it", "Defending pretty images that do not communicate the required story"], [kodak, resolveTraining, arriLight]),
  "Light Quality, Size & Distance": E("Light quality describes the transition and texture a source produces, chiefly controlled by its apparent size from the subject. Distance changes apparent size, intensity and the difference in exposure between near and far surfaces.", [
    { heading: "Apparent size controls shadow edge", body: "A large source close to the subject sends rays from many angles, wrapping around form and producing a broad penumbra. The same modifier moved far away appears smaller and becomes harder." },
    { heading: "Soft is not dim", body: "Hardness and intensity are independent. A large source can be bright and a bare small lamp dim; diffusion often costs output but its defining effect is increased emitting area or angular spread." },
    { heading: "Distance and falloff", body: "For a sufficiently small source in open space, illuminance follows the inverse-square relationship: doubling distance gives roughly one quarter the light. Large nearby sources and bounced environments depart from the simple point-source model." },
    { heading: "Distance controls spatial consistency", body: "A close source creates a large exposure difference between a near and far actor. A distant source changes less across the same blocking distance, which can improve continuity while becoming relatively harder." },
    { heading: "Choose from the desired surface", body: "Decide how skin texture, fabric, edges and shadows should read, then choose source size, position and diffusion. Fixture brand and wattage alone do not describe the image." },
  ], ["Predict shadow-edge changes from apparent size", "Separate quality from intensity", "Use distance to control falloff across blocking"], ["Move one softbox from one to four metres while resizing exposure", "Light two actors at different depths with close and distant sources"], ["Calling every diffused source soft", "Moving a source back to reduce level without noticing harder shadows", "Applying inverse-square math blindly to a large soft source"], [arriLight, kodak]),
  "Direction, Contrast & Modeling": E("Direction reveals or suppresses shape by deciding which planes receive light. Contrast organizes the difference between important values; modeling is the readable transition across form created by source direction, size, fill and surface response.", [
    { heading: "Direction describes planes", body: "Front light reduces visible relief, side light separates turning planes, backlight outlines and reveals atmosphere, and top or underlight reorders familiar facial cues. Height and azimuth matter more than labels." },
    { heading: "Contrast has multiple meanings", body: "Scene contrast compares luminances in the set; lighting ratio often compares incident contributions; image contrast depends on camera response and display transform. State what is being measured." },
    { heading: "Modeling needs a gradient", body: "A face reads as volume when light transitions across forehead, cheek and jaw while retaining purposeful eye information. Extremely frontal fill or uncontrolled bounce can erase that structure." },
    { heading: "Separation is contextual", body: "A rim is not mandatory. Subject/background separation can come from tone, color, focus, movement or atmospheric depth; an unjustified backlight may make a naturalistic room feel lit." },
    { heading: "Protect intent through the grade", body: "A contrasty monitor LUT may conceal shadow detail that exists, while aggressive lift can flatten modeled ratios. Record references and communicate which relationships must survive finishing." },
  ], ["Describe light by angle and height", "Distinguish scene, lighting and display contrast", "Model a face without defaulting to a rim light"], ["Rotate one key around a stationary bust", "Create separation first with tone and then with backlight and compare motivation"], ["Using front fill until all facial shape disappears", "Quoting ratios without a measurement definition", "Adding a hair light to every setup"], [arriLight, arriDR]),
  "Photometric Foundations & Falloff": E("Photometry gives practical quantities for visible light: lumens describe emitted flux, candela intensity in a direction, lux incident illumination, and luminance the light leaving a surface toward camera. These measurements support continuity and planning.", [
    { heading: "Measure the right event", body: "An incident meter measures illumination arriving at the subject; a spot meter estimates reflected luminance from a particular surface. Two equally illuminated materials can return very different camera values." },
    { heading: "Lux and foot-candles", body: "Lux is lumens per square metre; one foot-candle is about 10.76 lux. Meter readings become useful when connected to a tested exposure index, shutter and stop." },
    { heading: "Inverse square as a planning model", body: "For a point-like source, E = I/d². The relationship predicts both level and how quickly actors change exposure when moving near a source." },
    { heading: "Beam angle concentrates output", body: "Two fixtures with the same total flux can produce different lux because optics concentrate light into different angles. Compare photometric tables at the required throw and beam size, not nominal wattage." },
    { heading: "Surfaces rewrite readings", body: "Bounce reflectance, wall color, specularity and angle alter returned light. Measure the built scene and monitor RGB channels; calculation is a starting point, not proof." },
  ], ["Define lumen, candela, lux and luminance", "Apply inverse-square reasoning", "Read a fixture photometric table for distance and beam"], ["Meter one lamp at one, two and four metres", "Compare white and dark fabric under equal incident illumination"], ["Comparing fixture wattage as output", "Confusing incident and reflected readings", "Expecting ideal inverse-square results from a wall-sized bounce"], [arriLight, kodak]),
  "Key, Fill, Negative Fill & Ratio": E("Key is the dominant modeling source; fill controls shadow density; negative fill removes ambient return. Their relationship sets shape and mood, but a numerical ratio matters only when its measuring method and display pipeline are known.", [
    { heading: "Key names function, not fixture", body: "A window, bounce or practical can be the key if it establishes the principal direction and exposure relationship. The brightest visible object is not necessarily the key on the subject." },
    { heading: "Fill can be environmental", body: "Fill may come from sky, walls or floor rather than a lamp near camera. Its direction, color and size affect whether shadows feel open, muddy or artificially frontal." },
    { heading: "Negative fill restores subtraction", body: "Black fabric close to the unlit side absorbs room bounce, deepening tone and improving direction. It is often more natural than increasing key output, especially in small white rooms." },
    { heading: "Ratios require a protocol", body: "Key-to-fill contribution, lit-to-shadow reflected level and waveform code-value difference are different ratios. Record which method you use and recognize that tone curves alter the displayed result." },
    { heading: "Eyes and skin set practical limits", body: "Preserve the expression and skin texture the scene requires. A dramatic ratio that loses the performance or clips one channel has failed its narrative job." },
  ], ["Assign key and fill by function", "Use negative fill in reflective rooms", "Measure and communicate a ratio with a defined method"], ["Shape a window portrait using only white and black textiles", "Compare incident contribution ratio with waveform face-side values"], ["Assuming fill must sit beside camera", "Adding more key when unwanted bounce is the problem", "Calling an IRE difference a lighting ratio without explanation"], [arriLight, arriDR]),
  "Color, Mixed Sources & Practical Lights": E("Lighting color is spectral, not merely a Kelvin number. Mixed sources can establish time, place and depth, while practicals motivate direction and appear in frame; successful control balances spectrum, exposure, white balance and narrative logic.", [
    { heading: "CCT is one axis", body: "Correlated color temperature places a source near a warm–cool locus, while green–magenta deviation and spectral gaps affect rendering independently. Two 3200 K LEDs may not reproduce skin or fabric alike." },
    { heading: "Mix by relationship", body: "A cool window and warm lamp read when the camera balance preserves a believable difference and each source owns clear territory. Randomly overlapping colors on skin often produce contamination rather than depth." },
    { heading: "Practicals must perform two jobs", body: "An in-frame lamp needs a believable visible brightness and enough motivated influence on nearby surfaces. Replace bulbs, dim, diffuse or hide supplemental units while preserving the apparent source direction." },
    { heading: "Dimming changes sources", body: "Tungsten warms as it dims; many LEDs maintain nominal color but can shift, flicker or lose color quality. Test at the actual dim level and shutter setting." },
    { heading: "Control before correction", body: "Gel, exchange fixtures, block spill or assign separate zones when sources conflict. A global grade cannot independently repair differently lit regions or restore absent wavelengths." },
  ], ["Separate CCT, tint and spectral rendering", "Create an intentional mixed-light relationship", "Balance a practical's visible and lighting functions"], ["Stage warm bedside practical against cool dawn window", "Dim tungsten and LED sources while measuring color and flicker"], ["Matching sources by Kelvin display alone", "Letting every colored source overlap the face", "Expecting white balance to fix incompatible spectra"], [arriLight, bmManual]),
  "Lighting Faces, Spaces & Products": E("Different subjects ask light to reveal different properties. Faces need expression and dimensional skin; spaces need depth and motivated geography; products need controlled reflections that describe shape and material.", [
    { heading: "Faces are moving forms", body: "Place the key for eyes, cheek and jaw through the performance range, not one still pose. Skin highlights should reveal structure without uncontrolled channel clipping." },
    { heading: "Spaces need pools and pathways", body: "Light depth planes and practical zones so viewers understand where action can happen. Selective darkness is useful when entrances, exits and safety remain legible." },
    { heading: "Glossy products reflect the source", body: "On polished objects the camera sees reflected cards and modifiers, not simply illumination on the surface. Shape the reflection with large gradients and flags, then adjust object or camera angle." },
    { heading: "Texture needs angle", body: "Raking light reveals relief in fabric, wood and food; frontal light suppresses it. Diffusion changes edge transfer while polarization can manage some non-metallic glare." },
    { heading: "Continuity follows subject function", body: "Mark positions, heights, dimmer values and practical states. Recreate the relationships that define the object—not just a fixture diagram detached from blocking." },
  ], ["Light a face through its performance range", "Create navigable depth in a room", "Control reflections to describe product material"], ["Build a long highlight down a bottle with a vertical diffusion frame", "Create separate foreground and background pools in one room"], ["Lighting a glossy product with a small frontal source", "Approving a face only at its starting mark", "Filling every dark corner of a location"], [arriLight, kodak]),
  "Continuity, Safety & Efficient Setups": E("Lighting continuity preserves motivated direction, level, color and practical state across coverage. Safety and speed come from planning loads, heat, rigging, access and a base setup that adapts rather than being rebuilt for every angle.", [
    { heading: "Record reproducible facts", body: "Photograph fixture positions, label circuits and dimmers, record meter and camera readings, practical bulbs, diffusion and time of day. A diagram without levels cannot recreate the image." },
    { heading: "Design a base light", body: "Establish motivated sources for the space, then make small angle-specific refinements. This preserves continuity better than inventing an unrelated key for every close-up." },
    { heading: "Electrical safety is calculated", body: "Know voltage, fixture draw, circuit rating and existing loads; use rated distribution and residual-current protection where appropriate. Never defeat grounding or rely on connector shape as proof of capacity." },
    { heading: "Rig against predictable failure", body: "Use rated hardware, secondary safeties, sandbags and clear cable paths. Heat, wind, rain, overhead work and emergency exits require explicit controls and qualified crew." },
    { heading: "Schedule irreversible changes", body: "Capture wide shots while location daylight and practical geography are controlled, group setups by direction, and preserve reset time. Efficiency means fewer uncontrolled changes, not rushed unsafe work." },
  ], ["Document a relightable setup", "Adapt a base light across coverage", "Identify electrical, overhead and access hazards before energizing"], ["Create a lighting continuity book for a day-to-night room", "Relight three shot sizes by adjusting flags rather than moving the motivated source"], ["Running unknown loads from one outlet", "Removing safety cables for speed", "Changing practical dim levels between coverage without a record"], [arriLight, kodak]),
  "Motivated Lighting Chapter Boss": E("This assignment integrates motivation, exposure, color, continuity and safety into a short scene whose light changes with story. Every source should have a plausible world relationship even when the result is stylized.", [
    { heading: "Write the light's story", body: "Name apparent sources, time of day, emotional baseline and the beat at which direction, contrast or color changes. Motivation is a consistent cause, not a demand for realism." },
    { heading: "Survey and measure", body: "Record ambient levels, power, windows, practical sockets, reflective surfaces, rigging points and hazards. Decide what can be controlled and what must be scheduled." },
    { heading: "Build depth before polish", body: "Establish exposure and separation across action zones, then refine faces and textures. Confirm that blocking stays inside intentional light rather than only one actor mark." },
    { heading: "Manage color and highlights", body: "Test practical bulbs and LEDs on camera, choose white balance, and rank highlight texture. Use waveform and RGB scopes to prevent a stylized source from silently clipping a channel." },
    { heading: "Prove continuity and safety", body: "Deliver diagrams, readings and hazard controls with the finished scene. Screen shots in sequence and correct mismatched source direction or practical state before creative grading." },
  ], ["Design motivated sources around a dramatic change", "Execute controlled color and contrast across coverage", "Produce continuity and safety evidence"], ["A warm safe room invaded by pulsing exterior blue", "A product ritual lit by one motivated workbench practical and shaped reflections"], ["Hiding arbitrary lights by placing a lamp in frame", "Making the climax merely brighter", "Submitting no record of power, rigging or continuity decisions"], [arriLight, arriDR, kodak]),
  "Why the Camera Moves": E("Camera movement changes the viewer's position, attention and spatial knowledge over time. A motivated move has a precise narrative trigger and destination; stabilization is only the mechanical means used to express it.", [
    { heading: "Movement can reveal", body: "A track, rise or arc changes occlusion and parallax, exposing information unavailable from the starting viewpoint. The reveal should arrive when the story is ready, not merely when the rig can move." },
    { heading: "Movement can attach", body: "Following a subject shares effort, uncertainty or momentum; leading observes anticipation and destination. Distance and height decide whether the camera feels companion, witness, pursuer or judge." },
    { heading: "Movement redirects attention", body: "A pan can transfer interest between characters, while a push can narrow significance. If the frame changes without changing knowledge, relationship or feeling, stillness may be stronger." },
    { heading: "Stillness is part of movement grammar", body: "Starting or stopping can mark realization, refusal or arrival. Constant floating movement removes contrast and can make major beats feel no different from connective action." },
    { heading: "Name trigger, path and landing", body: "Write what causes the camera to move, what information changes along its route, and why it stops on the final composition. This sentence is a better equipment brief than 'make it cinematic.'" },
  ], ["Assign a narrative function to a move", "Design trigger, path and landing", "Choose stillness when movement adds no information"], ["Begin a push only when a character understands the clue", "Stop following when one character chooses not to enter"], ["Moving because dialogue is static", "Starting before the dramatic trigger", "Ending without a deliberate composition"], [kodak, djiSupport]),
  "Tripod, Head & Controlled Pans": E("A tripod creates a stable, repeatable viewpoint; the fluid head shapes pan and tilt resistance. Controlled operation depends on level, balance, drag, stance and a rehearsed start and finish—not force against a poorly prepared rig.", [
    { heading: "Secure the foundation", body: "Spread legs on stable ground, lock every stage, use appropriate feet, level the bowl and protect the footprint. Sandbag or restrain where required without creating a trip hazard." },
    { heading: "Balance before drag", body: "Slide the camera until tilt does not strongly fall forward or back, then set counterbalance. Drag controls feel, not payload imbalance; excessive drag on an unbalanced rig produces stick-slip motion." },
    { heading: "Frame both endpoints", body: "Set the final composition first, position the body comfortably there, then rotate to the start. This avoids twisting into an unstable stance during the most important landing." },
    { heading: "Accelerate and settle", body: "A pan needs a deliberate ease-in, controlled travel and ease-out unless a snap is intended. Use a light grip and body rotation so tiny hand corrections do not imprint on the head." },
    { heading: "Pan speed meets cadence", body: "High-contrast detail crossing frame at 24 fps can judder even on a perfect head. Rehearse on the target focal length, shutter and display; slow the move or change visual treatment when necessary." },
  ], ["Balance and set counterbalance before drag", "Execute repeatable pan endpoints", "Evaluate pan speed for frame cadence"], ["Pan between two actors and land before the second begins", "Repeat a slow architectural pan at several drag settings"], ["Using drag to hold an unbalanced camera", "Standing comfortably only at the start", "Blaming tripod mechanics for cadence judder"], [kodak, bmManual]),
  "Handheld Grammar & Body Mechanics": E("Handheld photography transmits selected bodily motion into the image. It can feel present, unstable, searching or intimate; good operation controls horizon, vertical bounce and framing while preserving the amount of imperfection the scene needs.", [
    { heading: "Define the instability", body: "Low-amplitude breath-like drift feels different from sharp reactive jolts or sustained running vibration. Specify the energy and frequency instead of asking for generically shaky footage." },
    { heading: "Build a stable body", body: "Keep the rig close to the center of mass, widen contact points, relax shoulders, bend knees and move from hips and feet. Tension produces high-frequency corrections and fatigue." },
    { heading: "Control the vertical axis", body: "Short rolling steps and a lowered center reduce rise and fall. Watch the horizon and background verticals; stabilization in the lens or body cannot fix every translation or parallax error." },
    { heading: "React to performance", body: "A handheld operator can anticipate a gesture, hesitate, or arrive late with intention. Random reframing feels like operator error unless the scene establishes the camera as a searching observer." },
    { heading: "Design for endurance and safety", body: "Rig weight, cable snag, backward travel and limited peripheral vision affect performance. Rehearse the path with a spotter and reduce payload before fatigue degrades both image and safety." },
  ], ["Describe a handheld motion signature", "Use stance and steps to manage unwanted vibration", "Operate responsively without random reframing"], ["Shoot one scene with calm shoulder drift and urgent reactive corrections", "Follow a walking subject while comparing heel-heavy and softened steps"], ["Adding shake in post as a substitute for viewpoint", "Locking arms rigidly", "Walking backward without a spotter"], [kodak, djiShake]),
  "Sliders, Dollies & Parallax": E("Linear camera travel reveals depth through parallax: near objects move across the frame faster than distant ones. Sliders and dollies differ in range and payload, but both require a purposeful axis, secure track, repeatable speed and coordinated focus.", [
    { heading: "Translation is not a zoom", body: "A dolly changes viewpoint, occlusion and relative scale; a zoom changes framing from one viewpoint. A dolly-zoom combines opposing changes to hold subject size while transforming the background relationship." },
    { heading: "Foreground gives movement evidence", body: "A lateral slide against a distant flat wall may appear static. A close edge, doorway or object creates faster parallax and makes even a short move spatially legible." },
    { heading: "Track direction changes meaning", body: "Pushing changes distance and often intimacy; pulling can reveal isolation or context; lateral travel compares or uncovers; an arc changes both profile and background relationships." },
    { heading: "Mechanics must disappear", body: "Level the support, secure endpoints, check wheels or bearings, distribute payload and rehearse starts. Bumps, flex and torsion become more visible on long lenses." },
    { heading: "Coordinate lens and focus", body: "Measure subject distance throughout the move and check close-focus limits, breathing and matte-box clearance. Speed changes require the focus puller and performer to share cues." },
  ], ["Use parallax to reveal depth", "Distinguish optical zoom from camera translation", "Prepare repeatable track and focus marks"], ["Slide past a foreground doorframe to reveal a character", "Execute a short dolly-zoom and explain its changing background scale"], ["Using a slider with no foreground relationship", "Touching the end stop during the take", "Designing a move beyond the lens's close-focus range"], [kodak, zeissCircle]),
  "Gimbal Movement Design": E("A gimbal stabilizes camera orientation across three axes but does not remove vertical translation, poor footsteps or weak framing. Effective gimbal work begins with mechanical balance and tuning, then shapes follow response, operator movement and narrative timing.", [
    { heading: "Balance with motors off", body: "The camera should remain near placed angles on tilt, roll and pan rather than swinging toward a heavy side. Rebalance after changing lens, filter, cable or accessory; motors should correct movement, not fight gravity continuously." },
    { heading: "Tune to payload", body: "Insufficient stiffness allows lag and drift; excessive stiffness produces vibration and noise. Auto-tune is a starting point, followed by an axis check under the intended movement." },
    { heading: "Follow settings shape operation", body: "Deadband determines how far the handles move before response; speed and smoothing determine acceleration and settling. Slow settings can miss fast action, while aggressive settings transmit small operator corrections." },
    { heading: "The fourth axis remains", body: "Three-axis gimbals hold orientation but footsteps still lift the entire camera. Keep the center low, take short smooth steps and use foreground lines to judge vertical bob." },
    { heading: "Plan transitions and endpoints", body: "Mode changes, low-to-high passes and handoffs need clearance for arms, cables and the operator. A stabilized move is successful when it lands precisely, not merely because its middle is smooth." },
  ], ["Mechanically balance all three axes", "Tune stiffness and follow behavior for a shot", "Control vertical movement and land a composition"], ["Compare lock and follow mode on a straight walk", "Tune high until vibration appears, then back off safely to learn the threshold"], ["Powering on before balance", "Expecting the gimbal to remove footsteps", "Using one follow preset for every move"], [djiSupport, djiShake]),
  "Blocking, Rehearsal & Focus": E("A moving shot is a coordinated event between actors, operator, focus, sound, lighting and grips. Rehearsal converts an attractive route into a repeatable performance by assigning marks, cues, speeds, sight lines and recovery plans.", [
    { heading: "Scout the complete volume", body: "Walk the path at camera height and focal length. Check door widths, reflections, light stands, floor changes, background reveals, wireless range and places where crew must hide or cross." },
    { heading: "Mark beats, not only feet", body: "Give movement cues from performance actions—turn, reveal, line or object pickup—so camera and actors share dramatic timing. Floor marks then support rather than replace those cues." },
    { heading: "Focus maps a changing geometry", body: "Measure critical distances, identify accelerations and rehearse sightline obstructions. Wireless focus needs motor calibration, secure gears and a monitor path tested through the whole route." },
    { heading: "Lighting must survive angles", body: "A moving camera may see behind flags or travel out of a source's coverage. Build motivated zones, coordinate dimmer cues or use blocking to pass naturally between them." },
    { heading: "Rehearse failure safely", body: "Define who calls stop, where the operator can bail out and how a missed mark resets. Use a spotter for blind or backward movement and keep emergency routes clear." },
  ], ["Map the full moving-shot volume", "Cue camera motion from dramatic beats", "Coordinate focus, light and safety across a path"], ["Rehearse a room-to-room follow with focus and dimmer cues", "Design a 360-degree move with planned crew hides"], ["Rehearsing camera without actors", "Marking only start and finish", "Letting wireless dropout or a blocked exit be discovered on the take"], [djiSupport, kodak]),
  "Rolling Shutter & Motion Artifacts": E("Many digital sensors expose or read rows at different times. Motion during that interval can bend verticals, skew pans, split flashes or create wobble; stabilization and flickering lights can interact with the readout to produce additional artifacts.", [
    { heading: "A frame has temporal structure", body: "With rolling shutter, the top and bottom of a nominal frame represent different moments. Readout time, distinct from exposure duration, sets the maximum displacement between those rows." },
    { heading: "Skew and lean", body: "During a horizontal pan, vertical lines appear diagonal because later rows see a later position. Faster readout, slower motion, wider framing or reduced angular velocity lessens the effect." },
    { heading: "Wobble and vibration", body: "High-frequency vibration changes direction during readout, making rigid objects appear gelatinous. Vehicles, overtuned gimbals, lens stabilization and flexible mounts can create or amplify it." },
    { heading: "Partial exposure events", body: "A brief flash may illuminate only some rows, producing a bright band. PWM lighting can form traveling dark bands when its cycle conflicts with frame exposure and readout." },
    { heading: "Test the recording mode", body: "Readout can change with resolution, crop and frame rate. Pan past vertical detail and test the actual stabilization, light and mount; a camera-wide specification may not apply to every mode." },
  ], ["Distinguish exposure time from sensor readout time", "Recognize skew, wobble and flash banding", "Reduce artifacts through mode, motion and rig choices"], ["Pan past lamp posts in each recording mode", "Mount the camera on a gently vibrating platform to identify jello"], ["Trying to fix rolling shutter only with a faster shutter", "Assuming all modes share readout speed", "Overtightening gimbal motors until vibration appears"], [bmManual, djiShake]),
  "Movement Sequence Chapter Boss": E("The movement sequence demonstrates that every camera path has narrative motivation, spatial clarity, repeatable mechanics and a controlled landing. It integrates stillness, support choice, blocking, focus, cadence and safety into an edited progression.", [
    { heading: "Create a movement vocabulary", body: "Assign distinct functions to locked, handheld, linear and stabilized behavior. Limit the vocabulary so a change in camera energy carries meaning." },
    { heading: "Previsualize spatial change", body: "Storyboard start, decisive intermediate reveal and final frame for every move. Include foreground parallax, axis effects and the information gained along the route." },
    { heading: "Choose the simplest support", body: "Use tripod, handheld, dolly or gimbal because its physical signature fits the beat. More complex equipment increases rehearsal and failure points without guaranteeing stronger storytelling." },
    { heading: "Engineer repeatability", body: "Document lens, stop, path, speed, focus marks, follow settings and cues. Rehearse entrances, transitions and emergency stops with the full payload and crew." },
    { heading: "Judge the sequence rhythm", body: "Edit the shots and inspect whether starts, landings and still moments create escalation and release. Remove any move whose only defense is smoothness." },
  ], ["Design a meaningful movement vocabulary", "Execute repeatable paths with coordinated focus", "Use movement and stillness to shape sequence rhythm"], ["A search that begins locked, becomes reactive handheld and resolves in one calm push", "A gimbal follow that stops before the character crosses a moral threshold"], ["Using every available rig", "Cutting before movements land", "Submitting smooth shots with no change in story information"], [djiSupport, djiShake, kodak]),
};
