export type KnowledgeSource = { title: string; url: string };
export type KnowledgeBlock = { heading: string; body: string };
export type TopicKnowledge = {
  summary: string;
  theory: KnowledgeBlock[];
  objectives: string[];
  examples: string[];
  mistakes: string[];
  sources: KnowledgeSource[];
};

const resolveManual: KnowledgeSource = { title: "DaVinci Resolve 21 Reference Manual (official)", url: "https://documents.blackmagicdesign.com/UserManuals/DaVinci_Resolve_21_Reference_Manual.pdf" };
const resolveTraining: KnowledgeSource = { title: "DaVinci Resolve official training books and project files", url: "https://www.blackmagicdesign.com/products/davinciresolve/training" };
const bmccManual: KnowledgeSource = { title: "Blackmagic Cinema Camera manual (official)", url: "https://documents.blackmagicdesign.com/UserManuals/BlackmagicCinemaCameraManual.pdf" };
const bmSupport: KnowledgeSource = { title: "Blackmagic Design support center", url: "https://www.blackmagicdesign.com/support/" };
const canonManual: KnowledgeSource = { title: "EOS M50 User Guide, firmware and downloads (Canon Europe)", url: "https://www.canon-europe.com/support/consumer/products/cameras/eos/eos-m50.html" };
const canonSupport: KnowledgeSource = { title: "EOS M50 support, downloads and specifications (Canon)", url: "https://www.usa.canon.com/support/p/eos-m50" };
const roninManual: KnowledgeSource = { title: "Ronin-M downloads and user manual (DJI)", url: "https://www.dji.com/downloads/products/ronin-m" };
const roninSupport: KnowledgeSource = { title: "Ronin-M product support (DJI)", url: "https://www.dji.com/support/product/ronin-m" };
const bfiLearning: KnowledgeSource = { title: "BFI filmmaking resources and opportunities", url: "https://www.bfi.org.uk/bfi-film-academy-opportunities-young-creatives" };
const adobeVideo: KnowledgeSource = { title: "Adobe video and filmmaking learning hub", url: "https://www.adobe.com/creativecloud/video/discover.html" };

const pack = (summary: string, theory: KnowledgeBlock[], objectives: string[], examples: string[], mistakes: string[], sources: KnowledgeSource[]): TopicKnowledge => ({ summary, theory, objectives, examples, mistakes, sources });
const b = (heading: string, body: string): KnowledgeBlock => ({ heading, body });

export const toolsCreativeKnowledge: Record<string, TopicKnowledge> = {
  "Project Manager, Libraries & Settings": pack(
    "A Resolve project contains edit decisions and metadata, while a Project Library is the database that holds projects. Neither is a backup of the camera originals. Settings establish the timeline, monitoring, cache, color and audio assumptions on which every later page depends.",
    [b("Library versus media", "A disk or PostgreSQL Project Library stores project records; imported clips still point to media elsewhere. Archive both project information and source media when portability matters."), b("Frame rate is structural", "Choose timeline frame rate before building the edit. Resolve restricts changing it after media is added because frame addresses, keyframes and audio timing depend on it."), b("Resolution is not frame rate", "Timeline resolution can usually change for alternate deliverables; timeline frame rate is a temporal base. Do not treat them as interchangeable setup choices."), b("Color and monitoring", "Project color management defines how encoded source values become timeline and display values. Monitoring hardware and display calibration determine whether the image you judge is trustworthy."), b("A recoverable beginning", "Name projects and libraries clearly, enable live save/project backups where appropriate, record storage paths, and test restoring a backup before production." )],
    ["Create a project with intentional frame-rate, resolution, color and cache settings.", "Explain what a Project Library backup protects and what it does not."],
    ["A 24 fps narrative project is configured before ingest and a restore test is documented.", "A social version changes timeline resolution while retaining the master timing."],
    ["Assuming a project backup contains original camera files.", "Editing first and discovering the timeline frame rate is wrong after synchronization."], [resolveManual, resolveTraining]),

  "Media Ingest, Metadata, Proxies & Relinking": pack(
    "Ingest is the controlled transition from camera media to verified, identifiable and relinkable editorial media. Metadata and stable file identity make proxies disposable performance aids rather than a second, ambiguous master.",
    [b("Copy before import", "Preserve the complete card or recorder structure, create at least two verified copies, and only then import. A visible file is not proof of an error-free copy."), b("Identity survives location", "Filename, timecode, reel metadata and folder structure let Resolve distinguish clips after drives move. Renaming source files mid-project weakens that chain."), b("Proxies are representatives", "Proxy media links lightweight files to camera originals. It should match duration, frame rate, timecode and audio well enough that switching to originals is deterministic."), b("Relink deliberately", "Relink selected clips or change source folders using the narrowest valid search path; then inspect first frame, last frame, timecode and audio rather than trusting a green online icon."), b("Metadata earns its keep", "Scene, shot, take, camera and good-take fields support bins, searches and conform checks. Enter metadata at ingest while production context is still available." )],
    ["Build a verified two-copy ingest and proxy workflow.", "Relink a moved project without replacing the wrong take."],
    ["A laptop edit travels with proxies, then reconnects to RAW originals for finishing.", "Smart bins collect circled takes using scene and take metadata."],
    ["Formatting media after an unverified drag-and-drop copy.", "Generating proxies with altered frame rate or missing production audio."], [resolveManual, resolveTraining]),

  "Cut Page: Fast Assembly Workflows": pack(
    "The Cut page is optimized for rapid selection and assembly through source tape, dual timelines and context-sensitive trimming. It is fastest when clips are already organized and the editor is choosing story material, not hunting through unnamed files.",
    [b("Source tape", "Source Tape presents a bin's clips as one browsable stream while edits still reference individual files. Sort order and metadata therefore change how the material is encountered."), b("Two timeline scales", "The upper timeline gives whole-program context; the lower timeline gives local precision. Together they reduce navigation without replacing intentional trimming."), b("Smart insert", "Smart Insert places a shot at the nearest edit indicated by the interface, so confirm the highlighted target before committing."), b("Append and overwrite", "Append is useful for chronological assemblies; overwrite replaces a defined duration. The commands encode different story intentions and should not be used merely because one is convenient."), b("Know when to leave", "Move to the Edit page when track topology, detailed keyframes or complex audio work becomes the problem. Page choice should follow the task." )],
    ["Assemble selects using Source Tape and explicit in/out decisions.", "Choose insert, append or overwrite based on the intended timeline change."],
    ["A documentary string-out is built from a metadata-sorted interview bin.", "B-roll is smart-inserted at a deliberately selected edit point."],
    ["Treating Source Tape as a new compound media file.", "Letting Smart Insert target an unseen edit without checking the indicator."], [resolveManual, resolveTraining]),

  "Edit Page: Timeline, Trim & Organization": pack(
    "The Edit page turns recorded material into a time-based argument. Track organization communicates editorial intent, while trim tools change story timing by moving an edit point, a shot, or the material inside a shot.",
    [b("Timeline grammar", "Video and audio tracks are layers with explicit selection, lock, mute and patch states. Labels and consistent track roles make later sound, VFX and delivery work auditable."), b("Ripple trim", "A ripple trim changes an edit point and the program duration downstream. It is appropriate when the event itself should occur earlier or later."), b("Roll trim", "A roll moves the shared cut while preserving total duration: one shot gains exactly what the neighbor loses."), b("Slip and slide", "A slip changes the visible source range without moving the clip; a slide moves the clip while compensating adjacent edits. Both preserve more structure than a remove-and-rebuild approach."), b("Selection discipline", "Track targeting, linked selection and sync locks determine what a command can disturb. Read those states before every consequential trim." )],
    ["Distinguish ripple, roll, slip and slide by what each preserves.", "Organize a timeline another editor can safely continue."],
    ["A reaction is slipped to land the glance without changing scene duration.", "A dialogue cut is rolled two frames to favor the listener while keeping the music cue fixed."],
    ["Dragging clips without noticing sync locks or track targets.", "Using blade cuts and gaps where a trim operation would preserve continuity."], [resolveManual, resolveTraining]),

  "Edit Page: Keyframes, Effects, Subtitles & Multicam": pack(
    "Keyframes describe change over time; effects process an image; subtitles carry timed language; multicam groups synchronized angles. Each solves a different editorial problem and requires a clean path back to the unmodified source.",
    [b("Interpolation shapes motion", "Two keyframes define endpoints, but easing defines acceleration. Inspect the curve when a move feels mechanical despite correct start and end values."), b("Effects order matters", "Transforming, reframing and processing in different orders can change edges, sharpness and render cost. Bypass effects to locate the first harmful operation."), b("Subtitle semantics", "Subtitle tracks contain timed caption events, not burned pixels. Preserve readable line lengths, speaker meaning and enough screen time for comprehension."), b("Multicam synchronization", "Angles can sync by common timecode, waveform or marked points. Verify long-recording drift and camera labels before switching live."), b("Commit with a reason", "Flattening multicam or baking effects removes flexibility. Duplicate the timeline and retain the editable construction before handoff." )],
    ["Animate a property with controlled interpolation rather than decorative motion.", "Build and verify a synchronized multicam clip and accessible subtitle track."],
    ["A scale move eases into a motivated detail as dialogue reveals it.", "A concert edit switches labeled angles while isolated audio remains continuous."],
    ["Using effects to disguise an editorial problem.", "Treating automatic captions as final without proofreading timing, names and meaning."], [resolveManual, resolveTraining]),

  "Fusion: Nodes, Masks & Compositing Logic": pack(
    "Fusion is a flow graph: images and masks move through tools toward an output. Reading the connections explains the composite more reliably than reading a stack of effect names.",
    [b("Image flow", "MediaIn supplies an image and MediaOut returns the result to the timeline. A disconnected branch does nothing, however elaborate it appears."), b("Merge roles", "A Merge combines foreground and background; swapping inputs changes spatial and alpha logic. Inspect the colored input roles rather than guessing."), b("Masks limit operations", "A polygon, ellipse or keyed matte connected to a blue mask input restricts a tool's effect. Feather changes transition width, not the underlying selection."), b("Order creates meaning", "Blur-before-key and key-before-blur produce different mattes; transform-before-merge differs from moving the completed composite. Follow the pixels."), b("Debug one node", "View intermediate nodes, bypass tools and inspect alpha. The first node where the image becomes wrong is more useful than changing downstream controls." )],
    ["Trace RGB and alpha from MediaIn to MediaOut.", "Construct and diagnose a masked foreground-over-background composite."],
    ["A window limits a grade-like glow to a practical lamp.", "A Merge places a keyed screen insert over a tracked plate."],
    ["Connecting two images without understanding foreground and background inputs.", "Adding compensating nodes after the alpha was already damaged."], [resolveManual, resolveTraining]),

  "Fusion: Tracking, Keying, Titles & Cleanup": pack(
    "Tracking estimates motion, keying estimates transparency, titles generate graphic elements, and cleanup reconstructs missing image areas. Convincing work joins these operations while preserving edge behavior, grain and motion blur.",
    [b("Track visible evidence", "Choose a region with persistent detail and compatible motion; a tracker cannot recover texture that leaves frame, changes shape or becomes occluded without intervention."), b("Planar versus point motion", "Point tracking follows features; planar tracking models a surface's translation, rotation, scale and perspective. Select the model that matches the object."), b("A key is an alpha estimate", "Pull the cleanest matte before despill. Judge opaque core, transparent background and fine transition detail separately."), b("Titles inhabit a shot", "Match perspective, motion blur, defocus, exposure and grain. Perfectly sharp, static type often exposes a composite more than imperfect tracking does."), b("Cleanup needs temporal proof", "A painted patch may work on one frame but reveal itself through parallax or changing light. Review the whole shot at speed and against a difference or alpha view." )],
    ["Choose point or planar tracking from scene geometry.", "Refine a key or cleanup through matte, edge and motion evaluation."],
    ["A planar track drives a phone-screen corner pin through perspective change.", "A wire removal uses a tracked clean patch with matched grain."],
    ["Tracking a reflective highlight as though it were attached texture.", "Softening a bad key until foreground detail disappears."], [resolveManual, resolveTraining]),

  "Color: Nodes, Primaries, Scopes & Matching": pack(
    "Color grading separates technical normalization, shot balancing and expressive shaping. Nodes preserve that reasoning; scopes reveal signal relationships that vision alone adapts away from.",
    [b("Primaries move broad relationships", "Lift, gamma and gain broadly influence shadows, midtones and highlights; offset shifts the whole signal. Their ranges overlap, so evaluate the complete image."), b("Scopes answer different questions", "Waveform shows level by horizontal position, parade separates channels, vectorscope shows chroma direction and strength, and histogram summarizes distribution without image location."), b("Node order is a pipeline", "A balance before a look is not equivalent to balancing after a clipped or selective operation. Name nodes by purpose so the signal path remains legible."), b("Match causes, not thumbnails", "Compare exposure, white balance, contrast, saturation and key subject values under the same viewing transform. A still-frame wipe reveals differences better than memory."), b("Protect latitude", "Avoid forcing legal or display limits early when later operations need highlight and gamut information. Evaluate clipping in scopes and at the delivery transform." )],
    ["Use scopes to balance exposure and color cast between shots.", "Build a node tree that distinguishes normalization, balance and look."],
    ["Two camera angles match at skin, neutral objects and contrast before a scene look is applied.", "A waveform identifies clipped highlights that the display roll-off concealed."],
    ["Matching only by copying node values between differently exposed shots.", "Reading a vectorscope as a spatial map of the frame."], [resolveManual, resolveTraining]),

  "Color Management, CSTs, Gamut & Gamma": pack(
    "Color management maps a source encoding through a working space to a display encoding. Gamut describes available chromaticities; gamma or transfer function describes how code values relate to light. Both must be identified for a transform to be meaningful.",
    [b("Tag the source truthfully", "An input tag describes how values are encoded, not how you want them to look. A wrong tag can produce a plausible but technically false result."), b("Working space buys room", "A wide-gamut, scene-referred timeline can retain values beyond the final display while grades are developed. It does not create information the camera never captured."), b("CST is explicit mapping", "A Color Space Transform converts named input gamut/gamma to named output gamut/gamma. Using it as a look without correct endpoints breaks predictability."), b("Avoid double transforms", "Log footage transformed by both project color management and an added CST may receive the display conversion twice. Trace input, timeline and output exactly once."), b("Tone and gamut mapping", "Mapping controls how out-of-range luminance and chroma enter a smaller display space. Inspect bright saturated details, not only neutral charts." )],
    ["Diagram source, timeline and output color spaces for a project.", "Detect an incorrect or duplicated transform using scopes and bypass tests."],
    ["CinemaDNG is decoded to a wide-gamut timeline and mapped once to Rec.709 output.", "An untagged graphic is assigned its actual sRGB-like source behavior before compositing."],
    ["Calling gamut and gamma the same property.", "Adding a display LUT after Resolve already performs the output transform."], [resolveManual, resolveTraining]),

  "RAW and CinemaDNG Debayer Workflow": pack(
    "CinemaDNG stores mosaiced sensor samples and metadata; debayering reconstructs RGB pixels. RAW controls such as white balance and exposure interpretation act before ordinary grading, so they should establish a sound negative rather than hide an unstable grade.",
    [b("A sequence is one clip", "CinemaDNG records numbered still frames plus audio separately or alongside camera media. Missing, renamed or nonconsecutive frames can break clip interpretation."), b("Debayer creates color pixels", "Each photosite samples limited color information; the decoder estimates complete RGB values using neighboring samples. Decode quality trades detail for processing cost."), b("Metadata is not baked certainty", "ISO and white balance commonly guide RAW interpretation rather than irreversibly altering sensor samples. Highlight clipping at capture, however, cannot be decoded back."), b("Project versus clip decode", "Project settings give a common starting point; clip decode overrides repair shot-specific exposure or white balance before the node graph."), b("Normalize once", "After debayering, map the chosen camera encoding into the managed timeline or display pipeline once. A LUT plus CST plus color management can silently triple-process the image." )],
    ["Explain the difference between sensor RAW, debayer settings and grading nodes.", "Conform a CinemaDNG sequence and choose an intentional decode quality and color path."],
    ["Half-resolution decode supports editing, then full quality is selected for final render.", "A clip-level RAW white-balance correction precedes shot matching."],
    ["Treating RAW exposure recovery as restoration of clipped photosites.", "Applying multiple normalization transforms because the image initially looks flat."], [resolveManual, bmccManual]),

  "Fairlight: Editing, Routing, Buses & Sync": pack(
    "Fairlight treats every audible result as a routed signal: clip to track, track processing to bus, bus to output. Editing fixes timing and selection; routing determines where the sound actually travels.",
    [b("Sync is relational", "Timecode, waveform and slate references can align recordings, but lips, transients and long-take drift must still be inspected."), b("Clip versus track", "Clip gain and clip effects address one event; faders, inserts and automation on a track affect everything routed through it."), b("Buses create stems", "Dialogue, music and effects buses permit group processing and separate deliverables. A Main bus represents the monitored or rendered sum."), b("Patch with intent", "Input/output patching and bus assignment can create silence or duplication even when meters move elsewhere. Follow the route stage by stage."), b("Room tone supports edits", "Continuous room tone conceals production cuts and preserves acoustic perspective; it should match microphone, position and room state." )],
    ["Trace a dialogue clip through track, bus and main output.", "Synchronize dual-system sound and verify drift across a long take."],
    ["Dialogue tracks feed a DX bus while music feeds an MX bus and both reach Main.", "A lav recording replaces camera scratch audio after waveform sync and phase check."],
    ["Raising the Main bus to repair one quiet clip.", "Assuming waveform sync is sample-perfect without checking mouth movement and phase."], [resolveManual, resolveTraining]),

  "Fairlight: EQ, Dynamics, Automation & Loudness": pack(
    "EQ reshapes frequency balance, dynamics control level relationships, automation changes parameters through time, and loudness measures the program over time. These are corrective and expressive tools, not substitutes for clean recording or intelligible balance.",
    [b("EQ by evidence", "Identify a resonance or masking conflict by listening in context, then use the narrowest effective change. Solo can diagnose, but the mix determines success."), b("Compression is level-dependent", "Threshold decides when gain reduction begins; ratio, attack and release shape how it responds. Makeup gain can fool louder-is-better comparisons."), b("Automation is performance", "Write fader or parameter movement to follow words, music phrases and perspective changes. Inspect automation mode before playback to avoid overwriting work."), b("Peak is not loudness", "True peak estimates intersample maximum; integrated loudness estimates perceived program level over duration. Delivery specifications may constrain both."), b("Measure the final route", "A bus limiter or later gain change alters delivery measurements. Meter at the endpoint and replay the exported file." )],
    ["Apply EQ or dynamics from an audible diagnosis and level-matched comparison.", "Measure integrated loudness and true peak on the final program route."],
    ["A dialogue resonance is reduced while consonant clarity remains intact.", "Music automation creates space for a line before returning naturally."],
    ["Compressing every track because compression is considered professional.", "Meeting a peak target while ignoring integrated loudness or intelligibility."], [resolveManual, resolveTraining]),

  "Deliver: Codecs, Containers, Channels & QC": pack(
    "Delivery packages encoded picture and sound for a destination. A container holds streams; codecs encode them; channel layouts give audio positions meaning. Quality control verifies both technical conformity and the actual viewing experience.",
    [b("Container versus codec", "MOV and MP4 are containers; ProRes, DNxHR and H.264 are codecs. A filename extension alone does not specify compression, bit depth or chroma sampling."), b("Render from the intended timeline", "Confirm resolution, frame rate, scaling, data levels, color tags and output transform. An otherwise clean render can be wrong because project and deliver settings disagree."), b("Channels have order", "Mono, stereo and multichannel renders require correct bus routing and channel mapping. Two active meters do not prove left and right contain the intended signals."), b("Compression has a purpose", "Use a robust master or mezzanine for preservation and a distribution encode for platform efficiency. Repeated lossy transcodes accumulate artifacts."), b("QC the file, not the promise", "Reimport or play the completed render from start to finish; inspect sync, first/last frames, titles, subtitles, black levels, audio channels and measured loudness." )],
    ["Specify container, video codec, audio layout and color behavior for a delivery.", "Perform a documented technical and content QC of the exported file."],
    ["A ProRes master feeds a separately encoded H.264 review copy.", "A stereo deliverable is checked on meters, headphones and a fresh player after export."],
    ["Calling an MOV file a codec.", "Watching only a few render sections and assuming the export is complete and synchronized."], [resolveManual, resolveTraining]),

  "Performance, Cache, Media Management & Troubleshooting": pack(
    "Resolve performance depends on decode cost, image processing, storage throughput, GPU memory and output resolution. Cache, proxies and optimized media intervene at different points, so diagnosis should identify the actual bottleneck before generating more files.",
    [b("Read the symptom", "Dropped playback may come from codec decode, Fusion, noise reduction, slow storage or an output too large for available GPU memory. Bypass stages one at a time."), b("Proxy versus optimized media", "Proxy media is portable alternate source media; optimized media is Resolve-managed performance media. Neither should become the only surviving copy."), b("Render cache", "Cache stores processed results for expensive timeline sections. It accelerates unchanged work but becomes stale or regenerates when upstream choices change."), b("Media management", "Consolidate or trim media with handles only after verifying retime, multicam, nested timeline and conform needs. Preserve the original archive."), b("Reproduce before reset", "Record the failing clip, page, node, codec and settings. A small reproducible project is more diagnostic than deleting caches and preferences indiscriminately." )],
    ["Isolate a playback bottleneck using controlled bypass tests.", "Choose proxies, cache or media consolidation for the problem each actually solves."],
    ["Disabling temporal noise reduction restores real-time playback, identifying GPU processing as the constraint.", "A traveling project uses linked proxies while camera originals remain on verified archive drives."],
    ["Generating every performance-media type without knowing which Resolve is using.", "Deleting project data while troubleshooting a cache problem."], [resolveManual, resolveTraining]),

  "Resolve End-to-End Chapter Boss": pack(
    "An end-to-end Resolve workflow proves that editorial, compositing, color, sound and delivery decisions remain coherent across pages. The challenge is controlled handoff between stages, not the number of tools used.",
    [b("Establish the contract", "Document frame rate, resolution, source encodings, audio layout, naming and deliverables before ingest."), b("Edit for meaning", "Lock story structure and track organization enough that finishing changes are traceable; preserve a version before conform work."), b("Finish in signal order", "Resolve only motivated VFX, normalize and balance color through one explicit pipeline, then mix through named buses."), b("Version deliberately", "Use timeline duplication and version names that identify purpose, date and status. Never let 'final' overwrite the only recoverable edit."), b("Prove the master", "Render a high-quality master and distribution copy, replay both, log QC results, and restore the project from its archived package." )],
    ["Complete and defend a reproducible camera-original-to-master workflow.", "Identify how a decision on one Resolve page affects at least two later stages."],
    ["A RAW short is conformed, graded, mixed and delivered with a source-to-output color diagram.", "A restore test opens the archived project and relinks its managed media on another drive."],
    ["Using every page whether or not the film needs it.", "Treating a successful render as proof that color, channels, sync and content are correct."], [resolveManual, resolveTraining]),

  "Body, Controls, Menus & Daily Operation": pack(
    "The original BMCC 2.5K is a manual cinema camera: a touchscreen configures recording and metadata, physical transport buttons control takes, and the operator must provide workable power, media, exposure tools and viewing conditions.",
    [b("Physical interface", "Transport keys provide record, stop and playback access; iris and focus assistance depend on compatible electronic lenses. Learn which control remains available with passive glass."), b("Menu consequences", "Recording format, frame rate, ISO, white balance, shutter angle and metadata affect the whole take. Read the status display before rolling."), b("Shutter angle", "A 180-degree angle keeps exposure time proportional to frame rate; changing frame rate changes exposure duration while the angle stays constant."), b("Touchscreen limits", "The fixed glossy rear display is for menus and basic monitoring, not reliable daylight focus or color judgment. Rig shade or external monitoring when stakes rise."), b("Daily discipline", "Inspect mount, ports and SSD door; format only cleared media; set slate metadata; roll a test; review picture and sound; then record the first slate." )],
    ["Configure the BMCC from a written camera report.", "Perform a power-on, record, playback and metadata preflight."],
    ["A 24 fps RAW setup is checked for shutter angle, ISO, WB, SSD time and audio before slate.", "An external monitor is used for focus while the rear screen remains the menu reference."],
    ["Assuming autofocus or autoexposure will rescue a rushed setup.", "Changing format or frame rate without announcing it to sound and post."], [bmccManual, bmSupport]),

  "2.5K Sensor, Crop & Image Character": pack(
    "The BMCC 2.5K sensor records 2432×1366 CinemaDNG and is smaller than Super 35 or full frame. Its crop changes field of view for a given lens, while its high dynamic-range log/RAW workflow favors protected highlights and deliberate finishing.",
    [b("Field of view", "Sensor dimensions, not a mystical lens multiplier, determine how much of a lens's image circle is recorded. The same focal length looks narrower than on a larger format."), b("Perspective comes from position", "Crop does not change perspective by itself. Moving backward to recover framing changes camera-to-subject geometry and therefore perspective."), b("Photosite exposure", "Highlight capacity is finite; a RAW container cannot restore saturated photosites. Expose from measured scene values and monitor clipping."), b("Resolution and detail", "2.5K capture permits a high-quality HD finish and modest reframing, but focus, lens contrast, debayer and aliasing still limit useful detail."), b("Character is a chain", "The perceived image comes from sensor response, lens, filtration, exposure, debayer, transform and grade. Do not attribute the entire look to sensor size." )],
    ["Predict framing differences between the BMCC and a larger sensor at the same position.", "Separate sensor behavior from lens, exposure and grading choices."],
    ["A wider lens maintains room coverage without moving the camera and changing perspective.", "A chart and real scene compare RAW detail after the intended debayer and HD downsample."],
    ["Calling crop factor a focal-length change.", "Expecting RAW to recover hard sensor clipping."], [bmccManual, resolveTraining]),

  "CinemaDNG RAW and ProRes Recording": pack(
    "CinemaDNG preserves sensor mosaics as frame sequences for extensive post interpretation; ProRes records debayered video for smaller, simpler workflows. The right choice follows latitude, storage, turnaround and finishing needs.",
    [b("RAW sequence", "Each CinemaDNG frame is a separate file; directory completeness and filename sequence are part of clip integrity."), b("ProRes is already RGB/YUV video", "The camera debayers and encodes ProRes before storage. It remains robust editing media but lacks the same pre-debayer controls."), b("Data-rate reality", "RAW consumes SSD capacity and offload time rapidly. Calculate minutes per drive and total copy windows before choosing it."), b("Dynamic range needs exposure", "Film/log encoding and RAW preserve grading flexibility only when the scene is exposed within sensor limits."), b("Choose by the weakest link", "A format is unsuitable if media, computer, backup or deadline cannot sustain it. Test the complete record-to-master path." )],
    ["Compare RAW and ProRes in data handling and post controls.", "Select a recording format from a documented production constraint."],
    ["RAW is reserved for a controlled VFX/grade sequence while ProRes covers long interviews.", "A camera test includes record duration, two verified offloads and a Resolve conform."],
    ["Choosing RAW solely because it sounds more cinematic.", "Copying only part of a DNG sequence or renaming individual frames."], [bmccManual, resolveTraining]),

  "Exposure, ISO, Highlights, WB & Tint": pack(
    "BMCC exposure places scene luminance within sensor capacity; ISO changes the monitoring/encoding interpretation rather than adding captured photons. White balance and tint guide neutral interpretation, while clipped highlights and underexposed noise remain capture consequences.",
    [b("Expose the sensor", "Aperture, shutter time, filtration and scene illumination determine photons. ISO changes how recorded values are mapped and monitored."), b("Protect meaningful highlights", "Use zebras and controlled tests to learn where important texture clips. Not every specular reflection needs detail, but faces and practicals may."), b("Shadow cost", "Lifting a severely underexposed RAW signal also lifts noise and fixed-pattern contamination. More grading latitude is not infinite latitude."), b("WB and tint axes", "Color temperature broadly balances blue–amber; tint corrects green–magenta bias. Set them from known light or a neutral reference, then judge skin and production color."), b("Consistency beats rescue", "Record exposure, ISO and WB per setup. Matching adjacent shots is easier when capture intent is documented." )],
    ["Explain which controls change captured exposure and which change interpretation.", "Place highlights and shadows deliberately using monitoring aids and a test grade."],
    ["A window highlight is allowed to clip while skin and wardrobe texture remain protected.", "A gray card establishes a neutral starting point under mixed practical light."],
    ["Raising ISO and believing the sensor received more light.", "Underexposing habitually because RAW is expected to remove noise later."], [bmccManual, resolveTraining]),

  "MFT Mount, Adapters & Lens Compatibility": pack(
    "The BMCC MFT uses a passive Micro Four Thirds mount: it offers short flange distance and broad mechanical adaptability but does not supply normal electronic iris, autofocus or stabilization control. Lens coverage and adapter geometry must be tested.",
    [b("Passive means manual", "Electronic-only aperture lenses may remain unusable or stuck because the body does not command them. Prefer lenses with mechanical focus and iris unless an adapter supplies control."), b("Flange distance", "A short native flange distance allows many longer-register lenses to reach infinity through a correctly machined adapter."), b("Coverage", "A lens must project an image circle large enough for the sensor; adapted still lenses usually do, while some C-mount or specialty lenses vignette."), b("Speed boosters are optical", "A focal reducer changes effective field of view and light concentration but adds optical surfaces and strict compatibility constraints."), b("Mechanical security", "Heavy lenses and adapters need support so torque is not carried by the camera mount. Check play, infinity focus and rear-element clearance." )],
    ["Determine whether a lens/adapter combination provides iris, focus, coverage and infinity focus.", "Rig adapted lenses without loading the MFT mount."],
    ["A manual Nikon F lens uses a simple adapter and lens support.", "An electronic EF lens is tested with an active adapter before the shoot."],
    ["Buying an adapter from mount names alone.", "Assuming the BMCC MFT electronically controls native MFT lenses."], [bmccManual, bmSupport]),

  "ND, IR Contamination & Filtration": pack(
    "Neutral-density filtration reduces light so aperture and shutter can serve motion and depth-of-field intent. On the BMCC, strong ND can reveal infrared contamination, shifting dark fabrics toward brown or magenta; IR-control strategy must be tested as a system.",
    [b("ND preserves exposure intent", "ND lowers scene light before the sensor without requiring a faster shutter or closed aperture."), b("Density is logarithmic", "Each stop halves transmitted light; stacked filters add density and additional reflecting surfaces."), b("IR leakage", "Some ND attenuates visible wavelengths more than infrared. The sensor may then record proportionally more IR, especially in synthetic black materials."), b("IRND and hot mirrors", "IRND combines visible and infrared attenuation; a hot mirror rejects IR but placement and angle can create reflections or color shifts."), b("Test the wardrobe", "Compare no-ND and shooting-density filtration on black cloth, skin and foliage under the actual sun and lens. Corrective grading cannot always separate contaminated materials." )],
    ["Calculate filtration needed to preserve a chosen shutter and aperture.", "Recognize and prevent BMCC infrared contamination."],
    ["Six stops of tested IRND hold a wide aperture outdoors without turning black fabric brown.", "A matte box shades a square filter to reduce flare."],
    ["Stacking unknown ND filters until exposure fits.", "Trying to white-balance away selective IR contamination."], [bmccManual, bmSupport]),

  "SSD Media, Capacity, Offload & Verification": pack(
    "The BMCC records to removable 2.5-inch SSDs whose sustained write performance and formatting must support the chosen codec. A finished take is not safe until it exists in multiple verified locations with its structure intact.",
    [b("Sustained, not advertised speed", "Peak speed on packaging does not guarantee continuous camera recording. Use supported or field-proven media and test full-drive takes."), b("Capacity planning", "Calculate expected data rate, shooting ratio and offload overlap. Leave operational headroom instead of planning to the final gigabyte."), b("Preserve structure", "Copy the complete shoot folder and DNG sequences without renaming frames. Use unique reel or drive identifiers."), b("Verification", "Checksum verification compares source and destination content, unlike a progress bar that reports only attempted copying."), b("Three-state media", "Mark media as exposed, copying or cleared; never rely on memory. Format only after two verified copies and explicit authorization." )],
    ["Plan SSD quantity and offload time for the selected recording format.", "Execute and log a checksum-verified two-destination offload."],
    ["A camera SSD is write-protected by procedure until two verified copies are logged.", "A full-duration RAW test confirms sustained recording before production."],
    ["Using any SSD that physically fits.", "Erasing after viewing copied filenames without checksum verification."], [bmccManual, bmSupport]),

  "Power, Internal Battery & External Supply": pack(
    "The BMCC internal battery is built in and best treated as a short bridge rather than an all-day source. Reliable production uses a compatible regulated external supply, secured cables, realistic runtime calculations and a safe changeover plan.",
    [b("Internal limits", "Age and temperature reduce built-in battery capacity. Test actual runtime under recording load rather than trusting an icon."), b("Voltage compatibility", "External batteries require the camera's specified input range, correct polarity and a suitable connector. Physical fit does not prove electrical safety."), b("Energy versus power", "Watt-hours estimate runtime; watts describe present demand. Include monitors, transmitters and converters in the rig total."), b("Cable management", "Strain-relieve the DC lead and prevent it entering the operator, gimbal or focus path. An intermittent connector can corrupt a take."), b("Changeover protocol", "Know whether the internal cell can bridge an external swap, monitor both states, and stop recording before uncertain power transitions." )],
    ["Calculate approximate rig runtime from watt-hours and load.", "Build and inspect a safe external-power path."],
    ["A V-mount plate powers camera and monitor through separately rated outputs.", "The internal cell bridges a documented battery swap after the take ends."],
    ["Using an unverified cable because the plug fits.", "Planning runtimes from a new-battery rating on an aged pack."], [bmccManual, bmSupport]),

  "Audio Inputs, Monitoring & Screen Limits": pack(
    "The BMCC can record production reference or usable sound through its inputs, but gain staging, connector format and monitoring require deliberate setup. Its rear screen does not replace dedicated audio meters, headphones and a focus/exposure monitor.",
    [b("Signal compatibility", "Mic and line sources have different levels; balanced and unbalanced connections reject interference differently. Match source, cable and camera input configuration."), b("Gain staging", "Set the source to provide a healthy signal while leaving transient headroom, then avoid excessive camera amplification that raises noise."), b("Monitor what is recorded", "Headphones reveal hum, clipping, clothing noise and absent channels. Meters alone cannot identify the cause."), b("Reference versus master sound", "If dual-system audio is the master, camera audio still aids sync and fault detection. Slate both systems and prevent scratch audio from masquerading as final."), b("Screen constraints", "The fixed display is vulnerable to glare and difficult viewing angles. Use magnification/peaking carefully and verify critical focus on suitable monitoring." )],
    ["Connect and gain-stage a microphone without clipping or avoidable noise.", "Define when BMCC audio is master, backup or synchronization reference."],
    ["A mixer sends a tested line feed while recording isolated production audio separately.", "A short playback check confirms both recorded channels before interviews begin."],
    ["Judging audio solely from moving meters.", "Assuming the rear screen is sufficiently accurate for daylight critical focus."], [bmccManual, bmSupport]),

  "Rigging, Tripod, Shoulder & Movement Limits": pack(
    "A BMCC rig should solve a shot's support, monitoring, power and control needs without creating unsafe leverage or exhausting the operator. The camera's box-like body becomes usable through balanced placement, not accessory accumulation.",
    [b("Start from the shot", "Tripod, shoulder and handheld work impose different center-of-gravity and access needs. Build only for the chosen movement."), b("Support the load", "Mount heavy batteries, matte boxes and lenses to rated rods or plates; secure every fastener and maintain access to media and ventilation."), b("Balance shoulder geometry", "Place mass around the shoulder so hands guide rather than continuously lift. Counterweight can reduce wrist load while increasing total mass."), b("Tripod dynamics", "Set head counterbalance and drag for the complete rig. A head below payload rating may tip or stick during pans."), b("Movement limit", "Rolling shutter, limited screen articulation and rig inertia constrain fast handheld motion. Stabilization cannot make every acceleration readable." )],
    ["Configure a minimal BMCC rig for tripod and shoulder scenarios.", "Evaluate payload, center of gravity and operator endurance before shooting."],
    ["A shoulder build moves the battery rearward to counterbalance lens and matte box.", "A tripod plate permits SSD access without dismantling the camera."],
    ["Adding a cage accessory because it is available rather than needed.", "Testing balance while omitting the actual battery, filter and cable load."], [bmccManual, roninManual]),

  "Rolling Shutter, Ronin-M Fit & Safe Motion": pack(
    "The BMCC reads its sensor over time, so rapid camera or subject motion can skew verticals and bend motion. A Ronin-M smooths angular movement but cannot remove readout skew; payload geometry and restrained acceleration remain essential.",
    [b("Readout is temporal", "Top and bottom rows are captured at different instants. Faster lateral motion makes their positional difference visible."), b("Stabilization is not correction", "A gimbal reduces operator rotation but rolling shutter remains when the camera pans quickly or vibration reaches the sensor."), b("Fit the complete build", "The BMCC, lens, cables and power arrangement must clear the Ronin-M frame through all axes and remain within payload limits."), b("Balance before motors", "Mechanical equilibrium minimizes motor force and vibration. Tune only after the exact shooting package holds position on each axis."), b("Move for legibility", "Slow starts, stops and pans; rehearse obstacle clearance; use a spotter when vision or footing is restricted." )],
    ["Predict motion likely to reveal rolling shutter.", "Assess and safely balance a complete BMCC package on the Ronin-M."],
    ["A slow lateral reveal replaces a whip pan across vertical architecture.", "Remote power is positioned so its cable cannot pull the tilt axis."],
    ["Expecting a gimbal to repair sensor skew.", "Tuning motors around a mechanically unbalanced camera."], [bmccManual, roninManual]),

  "CinemaDNG Import, Debayer & Color Management": pack(
    "BMCC CinemaDNG becomes a viewable color image only after Resolve groups the sequence, debayers it and maps its chosen camera encoding into a timeline and display. The workflow must preserve frame integrity and apply one intentional normalization path.",
    [b("Sequence integrity", "Keep sequential DNG filenames together; Resolve should see one clip of the expected duration, not thousands of unrelated stills."), b("Decode controls", "Choose project-level defaults, then use clip-level RAW overrides for genuine shot differences. Decode resolution can be reduced for performance without changing source files."), b("Camera interpretation", "White balance, exposure and highlight recovery operate in the RAW stage. They are strongest as negative preparation, not a substitute for lighting."), b("Managed route", "Assign the actual BMCC input behavior, work in a documented timeline space, and convert once to the intended output."), b("Conform proof", "Compare camera reports, first/last frame, duration and audio sync; then render a short test and reimport it before grading the production." )],
    ["Import a complete BMCC DNG sequence and configure its decode.", "Explain and verify the image path from RAW input through output display."],
    ["Editing uses a lower decode quality while final delivery returns to full-resolution debayer.", "A CST workflow is documented and project color management is disabled to avoid duplicate mapping."],
    ["Renaming DNG frames during offload.", "Applying a log-to-display LUT and an additional output transform unknowingly."], [resolveManual, bmccManual]),

  "BMCC Troubleshooting & Shoot Preparation": pack(
    "BMCC reliability comes from testing the exact camera, SSD, lens, filtration, power, sound and post path under production conditions. Troubleshooting should isolate one link and preserve evidence rather than reset the whole rig blindly.",
    [b("Reproduce the fault", "Record format, runtime, temperature, power source and connected accessories. Intermittent faults need repeatable conditions."), b("Media faults", "Dropped recording suggests sustained-write, formatting, connection or media-health problems. Test another proven SSD without erasing evidence."), b("Image faults", "Separate clipping, IR pollution, focus error, flare and monitoring mismatch using RAW inspection, scopes and controlled references."), b("Power and cable faults", "Remove nonessential accessories and test a known supply and cable. A rig-wide failure may originate in one shared power plate."), b("Preflight is a rehearsal", "Record, play back, offload, checksum, conform, grade and export the real format before call time; document spares and stop conditions." )],
    ["Use an isolation tree to diagnose a BMCC record, power or image fault.", "Produce a shoot-ready checklist proven by an end-to-end test."],
    ["An SSD failure is reproduced with long RAW takes and distinguished from battery interruption.", "A wardrobe/ND test catches IR contamination before principal photography."],
    ["Changing camera, cable, SSD and format simultaneously while debugging.", "Calling a five-second record test proof of sustained RAW reliability."], [bmccManual, bmSupport]),

  "BMCC RAW Chapter Boss": pack(
    "The BMCC RAW capstone joins exposure, lenses, filtration, support, power, media, sound and Resolve finishing into a recoverable cinema workflow. Success is a controlled negative and defensible master, not merely a pleasing grade.",
    [b("Design around the sensor", "Choose framing, motion and contrast that respect crop, rolling shutter and highlight capacity."), b("Build the camera", "Document lens control, filtration, support, monitoring, sound, power and SSD runtime for every setup."), b("Protect the negative", "Slate accurately and checksum full DNG sequences to two destinations before clearing media."), b("Interpret once", "Debayer at suitable quality, establish RAW white balance/exposure and use one explicit color-management route."), b("Defend with evidence", "Submit camera reports, exposure references, copy logs, node map, QC results and paired tests showing why the chosen workflow prevailed." )],
    ["Execute a complete BMCC CinemaDNG production-to-master chain.", "Diagnose and justify compromises in exposure, movement, storage and finishing."],
    ["A short scene includes a controlled highlight test and traceable DNG archive.", "The master is replayed and compared with a preserved neutral transform."],
    ["Grading an avoidable capture failure and presenting it as RAW flexibility.", "Delivering a film without proving the DNG archive can relink."], [bmccManual, resolveTraining]),

  "Controls, Menus & Daily Setup": pack(
    "The EOS M50 is mode-dependent: physical controls, touch interface and menu availability change with exposure and movie modes. A repeatable daily setup prevents the camera from silently choosing shutter, ISO, focus or color behavior.",
    [b("Choose movie intent", "Enter the intended movie mode before configuring, because still-photo settings and automatic movie modes may not share the same control."), b("Read the whole display", "Confirm frame rate, shutter, aperture, ISO, WB, Picture Style, AF method, card time and battery—not only the exposure meter."), b("Custom access", "Assign frequently used functions to buttons or the quick menu while protecting record control from accidental changes."), b("Reset selectively", "A known setup is useful, but clearing every setting can remove tested preferences. Record the desired baseline and verify after firmware or battery changes."), b("Daily test", "Record motion, speech and a focus transition; play it back with headphones or a computer before relying on the camera." )],
    ["Configure an M50 for a repeatable manual movie setup.", "Audit every displayed recording state before a take."],
    ["A 1080p project baseline is stored on a one-page camera setup card.", "A playback test catches an unintended automatic ISO choice."],
    ["Configuring the stills mode and assuming movie mode inherited it.", "Looking only at aperture and missing changed frame rate or AF method."], [canonManual, canonSupport]),

  "Exposure Behavior and Metering": pack(
    "The M50 meter estimates reflected light according to its metering pattern; it does not know the intended tone of the subject. Manual exposure fixes temporal consistency, while histograms and highlight alerts help distinguish a creative dark image from accidental clipping.",
    [b("Reflected meters seek a reference", "Bright snow may be darkened and a black room may be brightened because the meter interprets reflectance, not story intent."), b("Exposure variables", "Aperture changes light and depth of field, shutter time changes light and motion rendering, and ISO changes amplification/encoding with noise consequences."), b("Frame-rate relationship", "At 25 fps, a shutter near 1/50 s gives familiar motion blur; it is a starting point, not a law."), b("Histogram limits", "The brightness histogram summarizes encoded values and lacks spatial context. Inspect important highlights and channels where available."), b("Lock continuity", "Automatic exposure can visibly pump during reframing or subject movement. Use manual control or deliberate locking for shots that must cut together." )],
    ["Interpret meter bias on bright and dark subjects.", "Create consistent manual exposure for a moving shot while protecting important highlights."],
    ["A white wall is kept intentionally bright rather than forced to meter gray.", "A locked interview exposure prevents window changes from pumping the face."],
    ["Treating zero on the meter as objectively correct exposure.", "Changing shutter solely to fix brightness and damaging motion rendering."], [canonManual, canonSupport]),

  "Autofocus Modes and Focus Strategy": pack(
    "M50 autofocus behavior depends on recording resolution, AF method, lens, light and subject recognition. A focus strategy defines the subject, area, transition and fallback before recording rather than trusting a focus box.",
    [b("Mode changes capability", "Dual Pixel CMOS AF behavior available in common HD modes differs from contrast-based behavior in 4K. Test the exact format."), b("Area communicates priority", "Face tracking, zone and single-point methods tell the camera what evidence to privilege. A wide area may select the wrong nearby face or contrast edge."), b("Lens matters", "Focus motor design, maximum aperture and adapted-lens communication affect speed, noise and smoothness."), b("Transition is visible", "A fast refocus may snap unnaturally; a slow one may lag action. Rehearse entry, occlusion and exit at recorded speed."), b("Manual fallback", "Magnification and peaking assist manual focus but do not guarantee eye sharpness. Mark distance or use a repeatable pull when autofocus cannot infer intent." )],
    ["Select an AF method suited to a specific subject and recording mode.", "Design and test a manual fallback for occlusion or low contrast."],
    ["Single-point AF prevents a foreground prop from stealing focus during an interview.", "A 4K setup is tested separately rather than assumed to behave like 1080p."],
    ["Believing a face box proves the recorded eyes are sharp.", "Evaluating autofocus only with a static, well-lit subject."], [canonManual, canonSupport]),

  "Recording Modes, Codecs & Frame Rates": pack(
    "M50 recording modes change resolution, frame rate, crop, autofocus and data demand together. Codec and container choices determine compression and compatibility, while frame rate determines temporal sampling and must serve both acquisition and timeline intent.",
    [b("4K is a different operating mode", "On the original M50, 4K applies a substantial crop and uses different autofocus behavior from familiar HD modes. Reframe and refocus the test."), b("Frame rate is time sampling", "23.98/25/29.97 describe captured moments per second. Slow motion requires a deliberate capture and playback relationship, not merely changing a timeline number."), b("Shutter follows motion intent", "Higher frame rates often need shorter exposure times to retain similar blur angle, demanding more light."), b("Compression is finite", "Highly compressed files are efficient but can fail in fine motion, noise or repeated transcoding. Expose cleanly and preserve camera originals."), b("Limits are production facts", "Card speed, clip duration, battery, heat and file system behavior should be tested with a take longer than the planned maximum." )],
    ["Choose an M50 mode from resolution, crop, AF and motion requirements.", "Conform captured frame rate intentionally in the editing timeline."],
    ["HD is selected for dependable face tracking and wider field of view.", "High-frame-rate material is captured with adequate light and interpreted for planned slow motion."],
    ["Selecting 4K for quality without testing crop and autofocus.", "Changing timeline frame rate to force slow motion without understanding cadence."], [canonManual, canonSupport]),

  "Picture Styles, White Balance & Color": pack(
    "Picture Style shapes contrast, saturation and sharpness in encoded M50 video; white balance sets the camera's interpretation of illumination. Because the files offer less grading latitude than RAW cinema capture, restrained, consistent in-camera decisions matter.",
    [b("Style is processing", "Standard, Neutral and custom styles alter the recorded image, not merely the rear-screen preview. Excess sharpness and contrast are difficult to remove later."), b("Flat is not automatically better", "Reducing contrast may preserve some encoded range but can compress tones into limited data. Test against noise, banding and required turnaround."), b("WB continuity", "Auto WB can drift during a take or between angles. A fixed Kelvin/preset or custom balance stabilizes a scene."), b("Mixed light remains mixed", "One WB setting cannot neutralize sources with different spectra. Choose the key subject and control, gel or embrace the remainder."), b("Color pipeline", "Record the style and WB, avoid duplicate display transforms, and match shots before adding a creative look." )],
    ["Compare Picture Styles for contrast, sharpening and grading tolerance.", "Set repeatable white balance for a multi-shot scene."],
    ["A restrained Neutral customization protects skin texture without pretending to be log.", "A gray reference anchors two cameras under the same key light."],
    ["Calling a low-contrast Picture Style RAW or log.", "Leaving Auto WB active through a camera move between different sources."], [canonManual, canonSupport]),

  "EF-M Lenses, Adapters & Practical Choices": pack(
    "Lens choice on the M50 combines field of view, aperture, stabilization, focus behavior and handling. EF/EF-S lenses can communicate through Canon's adapter, but their size may undermine the compact body's balance; incompatible optical adapters change additional variables.",
    [b("Native geometry", "EF-M lenses match the short mount and compact body; lens stabilization and AF behavior remain model-specific."), b("Canon adapter", "A correctly supported EF-EOS M adapter preserves the flange relationship and electronic communication for compatible EF/EF-S lenses without changing focal length."), b("Field of view", "The APS-C sensor records a narrower angle than full frame at the same focal length. Perspective changes only if camera position changes."), b("Focus-by-wire", "Many compact lenses translate ring movement electronically, so repeatability and response differ from a mechanical cinema focus ring."), b("Choose the whole behavior", "Judge breathing, minimum focus, flare, stabilization interaction, motor noise and rig balance—not only maximum aperture." )],
    ["Select an M50 lens from framing, focus, light and support requirements.", "Explain what a non-optical EF adapter preserves and what sensor crop still changes."],
    ["A small native stabilized lens supports handheld documentary work.", "An adapted EF lens is supported when its mass overwhelms the camera mount."],
    ["Calling a simple adapter a speed booster.", "Choosing the fastest lens without testing focus noise or depth-of-field tolerance."], [canonManual, canonSupport]),

  "Strengths, Limits, Heat, Battery & Media": pack(
    "The M50's strengths are low mass, accessible controls and capable HD autofocus; its constraints include battery endurance, recording-mode compromises, compact handling and media/temperature limits. Reliability comes from designing shots around these facts.",
    [b("Small changes movement", "Low mass is easy to place but also easy to shake. Add support or body contact rather than assuming digital correction will save micro-jitter."), b("Battery planning", "Screen use, autofocus, stabilization and recording draw power. Test aged batteries and carry a labeled rotation."), b("Heat and duration", "Long takes and warm environments can interrupt compact cameras. Rehearse the longest planned take with recovery time."), b("Media compatibility", "Use cards meeting the camera's speed requirements, format in camera after verified backups, and monitor remaining time."), b("Exploit, do not deny", "Use the M50 where discretion, weight and fast face tracking matter; choose another tool when RAW latitude, robust connections or long continuous operation dominate." )],
    ["Build a realistic runtime and media plan for the M50.", "Choose scenarios that exploit the camera rather than conceal its limits."],
    ["A lightweight daytime insert unit uses the M50 while the cinema camera handles controlled RAW work.", "A long-event plan rotates bodies or schedules breaks after a full-duration heat test."],
    ["Bringing batteries without testing their actual recording runtime.", "Assuming a fast card cures every recording or heat limitation."], [canonManual, canonSupport]),

  "M50 Practical Scenario Chapter Boss": pack(
    "The M50 capstone asks for a complete, repeatable shooting decision: mode, lens, exposure, color, focus, sound, support, power and media must serve a real scenario and survive editorial handoff.",
    [b("State the scenario", "Define subject movement, duration, access, light, sound and delivery before touching a menu."), b("Select the mode", "Justify resolution and frame rate against crop, autofocus and post requirements."), b("Control the image", "Lock exposure and WB where continuity matters; choose a Picture Style whose processing fits the finish."), b("Rehearse failure", "Test occlusion, focus fallback, battery change, card capacity and the longest take."), b("Close the loop", "Offload and verify, edit a representative sequence, inspect compression and color, and revise the camera plan from evidence." )],
    ["Configure and defend an M50 package for a specified production scenario.", "Demonstrate that the recorded files remain coherent through edit and delivery."],
    ["A solo documentary setup prioritizes HD face AF, compact stabilized glass and redundant sound.", "A locked-off interview uses mains strategy, manual exposure/WB and monitored external audio."],
    ["Choosing settings from maximum specifications instead of scenario needs.", "Completing the shoot test without an actual edit and export."], [canonManual, canonSupport]),

  "Hardware, Payload & Safety Inspection": pack(
    "The Ronin-M is a motorized three-axis support whose frame, stand, handles, battery, clamps and wiring must safely carry the complete camera package. Payload rating is only one constraint; clearance and center of gravity determine whether the rig can balance and move.",
    [b("Inspect before power", "Check frame damage, clamp engagement, fasteners, motor cables, battery seating and stand stability before mounting a camera."), b("Complete payload", "Weigh camera, lens, filter, plate, cables and onboard power. A lens change can shift both mass and geometry."), b("Clearance envelope", "Rotate each unpowered axis through its planned range and ensure camera, viewfinder and cables do not strike the frame."), b("Stand protocol", "Use the tuning stand on stable level ground, hold the rig during mounting, and never leave a loaded gimbal unattended."), b("Operator zone", "Plan lifting, handoff and emergency power-down; keep people clear during auto tune and calibration." )],
    ["Inspect and mount a complete Ronin-M payload safely.", "Distinguish weight compliance from actual balance and clearance."],
    ["A lens and filter change triggers a new balance and clearance check.", "Two operators rehearse lifting from stand to ring handles before talent enters."],
    ["Powering motors while an axis is mechanically obstructed.", "Checking camera weight but omitting accessories and cable drag."], [roninManual, roninSupport]),

  "Mechanical Balance on Three Axes": pack(
    "Mechanical balance places the camera's center of gravity on the tilt, roll and pan axes so it can hold position unpowered. Motors then correct motion rather than continuously fighting gravity.",
    [b("Prepare the exact build", "Install charged battery, card, lens, filter, focus position and every required cable before balancing."), b("Tilt axis", "Balance vertical tilt position and fore-aft camera position so the lens holds at level and angled positions without falling."), b("Roll axis", "Shift laterally until the camera remains level rather than dropping to one side."), b("Pan axis", "Tilt the entire gimbal on the stand and adjust the pan arm until it no longer swings downhill."), b("Iterate and lock", "Axes interact, so repeat the sequence with small changes, tighten clamps, and confirm free movement before power." )],
    ["Balance tilt, roll and pan with motors off.", "Diagnose which adjustment corresponds to a specific falling direction."],
    ["The camera remains at a 45-degree tilt without drifting after both tilt adjustments.", "Tilting the stand reveals a pan-axis imbalance invisible when upright."],
    ["Using motor stiffness to hold an unbalanced camera.", "Balancing without the filter or cable used during the take."], [roninManual, roninSupport]),

  "Auto Tune, Stiffness & Calibration": pack(
    "Auto Tune estimates motor stiffness for the balanced payload; stiffness supplies corrective authority but excessive values create vibration. Calibration establishes sensor references and should address a demonstrated drift or horizon problem, not replace balance.",
    [b("Tune after balance", "Auto Tune assumes free, balanced axes. Run it on the stand with the exact payload and no obstruction."), b("Stiffness threshold", "Increase stiffness only until the axis holds responsively; high-frequency buzzing or visible vibration indicates excessive gain or structural flex."), b("Strength and filtering", "Additional motor controls shape response and noise. Change one setting at a time and record the baseline."), b("System calibration", "Calibrate on a stable, level, motionless support when instructed. Moving the rig during calibration corrupts its reference."), b("Dynamic proof", "Test static hold, slow walk, acceleration, tilt and the actual lens field of view; a wide lens can hide vibration that a longer lens reveals." )],
    ["Auto-tune a balanced package and refine stiffness from observed behavior.", "Decide whether drift originates in balance, calibration or control input."],
    ["A longer lens reveals roll oscillation and stiffness is reduced incrementally.", "A verified level surface supports calibration after persistent horizon error."],
    ["Calibrating repeatedly to fix cable pull.", "Maximizing stiffness because stronger motors seem more stable."], [roninManual, roninSupport]),

  "Modes, Remote and Operator Control": pack(
    "Ronin-M operating modes decide how pan, tilt and roll respond to the handles or remote. SmoothTrack converts operator rotation into controlled following; remote control separates framing from the carrier's movement.",
    [b("Follow behavior", "Deadband sets how much operator rotation is ignored, speed sets follow rate, and smoothing shapes starts/stops. Together they define feel."), b("Mode follows shot", "Upright, underslung and briefcase orientations change handling and clearance. Transition only as the manual permits and rehearse unpowered geometry."), b("Remote division", "A remote operator can frame while a carrier navigates, but both need shared cues, limits and an agreed neutral orientation."), b("Control priority", "Unexpected motion can come from remote sticks, SmoothTrack or calibration drift. Disable one source at a time to diagnose."), b("Return and endpoints", "Set safe travel and recenter behavior so the camera cannot hit the frame or whip toward talent." )],
    ["Configure follow response for a stated camera move.", "Coordinate carrier and remote operator with clear control boundaries."],
    ["Low follow speed and smoothing create a gentle reveal after the carrier turns.", "A remote operator maintains eyeline framing while the carrier watches footing."],
    ["Changing three response parameters without recording their effects.", "Letting both carrier and remote operator fight for composition."], [roninManual, roninSupport]),

  "Power, Batteries & Field Setup": pack(
    "Ronin-M field reliability depends on correctly handled intelligent batteries, secure installation, realistic runtime and a setup area where the loaded gimbal can be mounted, tuned and transferred safely.",
    [b("Battery condition", "Inspect for swelling, impact, damaged contacts or abnormal heat; follow DJI charging and storage guidance and retire unsafe packs."), b("Runtime is load-dependent", "Motor demand rises with imbalance, wind, acceleration and payload. Measure production runtime instead of relying on nominal values."), b("Change safely", "Power down, support the gimbal on its stand, replace the battery, then confirm clamps and balance before restarting."), b("Field station", "Create a protected area for the stand, tools, charged/used battery separation and camera rebuilds away from traffic."), b("Cold and transport", "Temperature affects battery performance; transport and store packs according to current safety rules, with terminals protected." )],
    ["Operate a labeled Ronin-M battery rotation with safety inspection.", "Design a stable field setup and changeover procedure."],
    ["A timed rehearsal establishes a conservative runtime including wind and repeated acceleration.", "Used batteries move to a separate marked case rather than back beside charged packs."],
    ["Hot-swapping while the loaded gimbal is handheld.", "Ignoring rapid battery depletion caused by poor balance."], [roninManual, roninSupport]),

  "Walking, Starts, Stops & Parallax": pack(
    "A gimbal controls camera orientation, not the operator's vertical translation or path. Soft footwork, progressive acceleration and spatial planning create stable movement; foreground/background relationships create parallax and therefore the shot's sense of depth.",
    [b("Body isolation", "Bend knees, shorten steps and keep the rig near a stable body center. The pan motors cannot remove each rise and fall of the carrier."), b("Ease velocity", "Begin and end through gradual body acceleration; sudden force produces horizon, bob and framing corrections."), b("Parallax communicates space", "Moving close to foreground objects creates faster relative motion than the background. Distance and path determine the strength of the effect."), b("Look where feet go", "A spotter protects the carrier when moving backward or through obstacles. The image never outranks physical safety."), b("Rehearse the exit", "Plan where the move settles and how the operator stops without a final bump; hold the ending long enough for editorial use." )],
    ["Perform a repeatable start, path, stop and hold with reduced vertical bob.", "Design foreground parallax to reveal depth without distracting from the subject."],
    ["A slow doorway pass uses the frame edge as foreground reveal.", "The operator lands on a marked stance and holds ten seconds after action."],
    ["Walking normally and expecting three motors to remove vertical bounce.", "Moving backward without a spotter because the monitor occupies attention."], [roninManual, roninSupport]),

  "BMCC and M50 Build Decisions": pack(
    "The Ronin-M build must accommodate two very different bodies: the dense, box-shaped BMCC with external-power and monitoring needs, and the light M50 with articulated controls and lens-dependent stabilization. Each build needs its own plate position, cable route, tune and shot limits.",
    [b("BMCC geometry", "The BMCC's mass and box form may challenge tilt clearance; keep SSD access, power cable and screen/monitor strategy in the balance plan."), b("M50 geometry", "A very light M50 package may need plate positioning or approved counterweight to reach axis adjustment ranges. The flip screen and lens extension need clearance."), b("Lens changes are rebuilds", "Zoom extension, focus movement and adapter mass shift center of gravity. Balance in the actual operating state."), b("Stabilization interaction", "Lens or digital stabilization may fight gimbal movement or alter framing. Compare it on and off during the actual move."), b("Select by shot", "Choose BMCC for RAW image priorities when the rig can carry its workflow; choose M50 when low mass, access or AF matters. The gimbal does not erase camera differences." )],
    ["Build, balance and compare BMCC and M50 Ronin-M packages.", "Select the camera package from shot and workflow requirements."],
    ["A lightweight M50 setup gains clearance for a high-to-low move.", "A BMCC build keeps power onboard with slack that cannot steer the pan axis."],
    ["Reusing motor settings after swapping cameras.", "Routing an external cable off-gimbal so it behaves like a spring."], [roninManual, bmccManual, canonManual]),

  "Ronin-M Troubleshooting & Chapter Boss": pack(
    "The Ronin-M capstone proves safe preparation, mechanical balance, tuning, operating design and diagnosis through a motivated shot. Troubleshooting follows mechanics, clearance, cables, tune, calibration and control inputs in that order.",
    [b("Classify the symptom", "Buzz is commonly excessive stiffness or flex; slow drift suggests balance, calibration or input; violent shaking demands immediate shutdown and obstruction inspection."), b("Return to mechanics", "Power off and verify all three axes, locks and clearances. Software cannot repair a slipping plate."), b("Isolate influence", "Disconnect or disable remote control, external cables and optional accessories one at a time to locate steering forces."), b("Shoot with intent", "Define why the camera moves, its subject relationship, start/end composition, safe route and editorial handles."), b("Document the solution", "Record payload, axis positions, tune values, mode, path, runtime and fault corrections so the setup can be rebuilt." )],
    ["Diagnose a Ronin-M fault without unsafe trial and error.", "Deliver a repeatable motivated stabilized shot with setup evidence."],
    ["High-frequency vibration disappears after correcting plate flex and lowering roll stiffness.", "A corridor move has a spotter, foreground reveal, controlled stop and ten-second tail."],
    ["Continuing to hold a violently oscillating powered rig.", "Presenting a smooth but narratively unmotivated orbit as mastery."], [roninManual, roninSupport]),

  "Constraint Study: One Space, Five Meanings": pack(
    "This study proves that cinematic meaning is constructed, not contained in a location. The same space must communicate five distinct dramatic readings through controlled changes in blocking, framing, light, lens, sound and duration.",
    [b("Hold the world constant", "Keep location and core action stable so changes in interpretation can be traced to craft decisions."), b("Define five verbs", "Use playable meanings such as conceal, threaten, welcome, isolate and discover rather than vague style labels."), b("Change visual hierarchy", "Placement, contrast, focus and movement determine what the viewer reads first and what remains uncertain."), b("Sound redraws space", "Room tone, offscreen cues, reverberation and silence can make identical walls feel safe, exposed or haunted."), b("Compare as a sequence", "Screen versions in random order without titles and collect the meaning viewers infer before explaining intent." )],
    ["Create five legibly different dramatic meanings in one unchanged location.", "Identify which craft variable caused each audience inference."],
    ["A doorway becomes refuge through warm interior sound and stable framing, then threat through negative space and an offscreen approach.", "One static composition changes meaning through blocking and sound alone."],
    ["Changing every object and performance until the location is no longer a constant.", "Labeling versions with emotions and mistaking recognition of the label for successful communication."], [bfiLearning, adobeVideo]),

  "Light and Lens Controlled Comparison": pack(
    "A controlled comparison isolates how lens choice, camera position and lighting geometry shape faces, space and attention. Its value is causal evidence: one visible change should correspond to one deliberate variable.",
    [b("Fix the reference", "Mark subject, camera, focus target, exposure reference and display transform before versioning."), b("Focal length versus distance", "Changing focal length at fixed position changes framing; moving to restore framing changes perspective. Record both positions."), b("Light geometry", "Direction and apparent source size shape highlight, shadow and texture; intensity alone does not describe quality."), b("Normalize fairly", "Match important exposure values when comparing shape, or clearly state when exposure is itself the variable."), b("Judge motion too", "Rack focus, breathing, flare and subject movement can reveal differences invisible in a still chart." )],
    ["Design a single-variable lens or lighting comparison.", "Explain observed perspective, depth, texture and contrast changes causally."],
    ["Three focal lengths are tested both from fixed position and with matched subject size.", "A key source moves closer and grows larger while face exposure is rematched."],
    ["Changing lens, distance, aperture and light level between two unlabeled shots.", "Selecting the prettier still without evaluating movement or scene continuity."], [bfiLearning, adobeVideo]),

  "Dialogue Scene Micro Project": pack(
    "A short dialogue scene integrates dramatic objectives, eyelines, coverage, performance continuity, production sound and editorial listening. The scene succeeds when attention follows changing intentions rather than a checklist of angles.",
    [b("Map the turn", "Identify what each character wants and the exact beat where power, knowledge or tactic changes."), b("Stage before coverage", "Block bodies and eyelines in a coherent space; choose the axis from the relationship, then decide if crossing it has meaning."), b("Coverage has a job", "Capture masters, singles or inserts according to likely performance and information needs, with entrances, exits and reaction handles."), b("Record the room", "Protect dialogue microphone position, room tone and wild lines. A beautiful reverse angle is unusable if its sound cannot cut."), b("Edit the listener", "Dialogue scenes often live in reactions and pauses. Cut on the transfer of thought, not automatically on each spoken line." )],
    ["Direct and cover a scene around a clear dramatic turn.", "Edit intelligible space, continuous sound and performance-driven reactions."],
    ["A held reaction reveals the lie before the speaker finishes.", "A master protects body timing while selective singles intensify the reversal."],
    ["Shooting symmetrical coverage without knowing which beat each setup serves.", "Ignoring room tone and forcing every cut to remain on the speaker."], [bfiLearning, resolveTraining]),

  "Visual Music and Rhythm Study": pack(
    "This study explores rhythm created by image duration, internal movement, graphic recurrence and sound—not by cutting mechanically on every beat. Visual and sonic phrases can align, anticipate, resist or counterpoint each other.",
    [b("Find visual pulses", "Motion starts, gaze shifts, light changes and compositional impacts create accents before music is added."), b("Phrase, do not count only", "Musical bars contain tension and release; cutting at phrase boundaries can matter more than matching every transient."), b("Sync has degrees", "Exact synchronization emphasizes impact; near-sync creates propulsion; counterpoint creates friction or independent meaning."), b("Duration changes reading", "Give each shot enough time for its information, then test how repetition and variation alter expectation."), b("Build without the track", "Create a silent visual rhythm first, then test several sound structures so the music supports rather than authors every decision." )],
    ["Construct a visual phrase with repetition, variation and release.", "Use synchronization or counterpoint for a stated perceptual effect."],
    ["A cut anticipates a downbeat, making the new motion land on it.", "A calm sound phrase continues across increasingly fragmented images to create unease."],
    ["Cutting on every beat until image meaning becomes unreadable.", "Using a copyrighted track without planning exhibition or replacement."], [adobeVideo, resolveTraining]),

  "Documentary Observation Mini Project": pack(
    "Observational documentary requires patience, ethical presence and responsive craft. The filmmaker gathers behavior, environment and consequences without pretending the camera is invisible or manufacturing reality for coverage.",
    [b("Consent is continuous", "Initial permission does not answer every later use. Explain context and revisit consent when vulnerability, location or distribution changes."), b("Learn the routine", "Observe before optimizing shots. Repeated actions reveal likely positions, transitions and moments of consequence."), b("Record relationships", "Wide context, process detail, faces, offscreen sound and aftermath allow an edit to preserve causality rather than assemble attractive fragments."), b("Intervene transparently", "Safety and dignity outrank noninterference. If an action is repeated or staged, record that production fact for editorial honesty."), b("Edit claims carefully", "Shot order implies cause, knowledge and motivation. Distinguish what was witnessed from what the sequence merely suggests." )],
    ["Film an unfolding activity with informed, revisitable consent.", "Edit a truthful temporal and causal account from observational material."],
    ["A work process is covered through preparation, action, reaction and result without asking for a false repeat.", "A consent conversation identifies material the participant does not want publicly contextualized."],
    ["Calling candid access consent.", "Reordering events to create a causal accusation unsupported by observation."], [bfiLearning, adobeVideo]),

  "Genre Reconstruction": pack(
    "Genre reconstruction reverse-engineers how a recognizable scene produces expectations through story information, staging, lensing, light, sound and editing. The goal is transferable grammar, not a costume-level imitation.",
    [b("Describe the promise", "State what the reference makes the audience anticipate and when that promise changes."), b("Break down systems", "Map shot scale, camera height, movement, contrast, color, sonic perspective, duration and performance behavior separately."), b("Find production causes", "Infer plausible source size, blocking, focal relationship and edit construction, then test rather than copying surface color."), b("Translate constraints", "Rebuild the function with available location, cast and equipment. A different object can carry the same reveal structure."), b("Introduce authorship", "After a faithful diagnostic version, alter one governing rule and evaluate whether genre legibility survives." )],
    ["Reverse-engineer a genre scene into reproducible craft decisions.", "Create an original reconstruction that preserves function without copying assets."],
    ["A suspense reference is mapped by delayed information and offscreen sound, then rebuilt in a different location.", "A second version breaks the lighting convention while retaining shot and sound grammar."],
    ["Matching a color grade while ignoring blocking and information order.", "Reproducing copyrighted dialogue, music or imagery when structural study would suffice."], [bfiLearning, adobeVideo]),

  "Complete Short Scene Integration Boss": pack(
    "The integration boss produces a complete short scene whose story, image, movement, sound, edit and color decisions support one dramatic change. Every technical choice must survive the entire path from plan to verified master.",
    [b("One scene, one change", "Define the entering condition, decisive turn and leaving condition so craft can prioritize the same dramatic event."), b("Preproduce dependencies", "Break down cast, location, safety, light, sound, coverage, media, power and post tests; identify the failure that would make the scene unfinishable."), b("Capture editorial evidence", "Slate, record room tone, protect performance and collect only coverage with a clear assembly purpose."), b("Finish coherently", "Lock structure, repair only motivated composites, balance and shape color through an explicit pipeline, and mix perspective before loudness."), b("Verify and reflect", "Replay the master, collect timecoded feedback, compare intent to audience reading, and name one workflow change for the next scene." )],
    ["Deliver a dramatically coherent short scene with recoverable production evidence.", "Defend cross-department decisions through audience and technical results."],
    ["A two-minute reversal scene uses a single motivated move at the dramatic turn.", "The archive contains plan, camera/sound reports, verified media, Resolve project and QC log."],
    ["Expanding scope until the central change cannot be rehearsed.", "Treating technical polish as proof the scene communicates its intended turn."], [bfiLearning, resolveTraining]),

  "Portfolio Curation & Reflective Practice": pack(
    "A portfolio is an argument about judgment, not a storage folder. Curation selects work for a particular audience, supplies enough context to understand responsibility, and uses reflection to turn successes and failures into the next repeatable practice.",
    [b("Choose the audience", "A cinematography collaborator, directing program and client need different evidence. Define the viewer and desired next conversation."), b("Edit ruthlessly", "Lead with strongest relevant work, remove repetition and preserve only enough duration to reveal decision-making, performance or progression."), b("Credit precisely", "State role, collaborators, tools and constraints. Never imply authorship of grade, sound, production design or direction you did not perform."), b("Show process selectively", "A test, lighting plan, node map or before/after can demonstrate thinking when it clarifies rather than excuses the result."), b("Reflect causally", "Describe intention, evidence, mismatch, cause and next experiment. 'I learned a lot' does not produce a usable change in practice." )],
    ["Curate and sequence a role-specific portfolio with accurate credits.", "Write evidence-based reflection that produces a concrete next experiment."],
    ["A cinematography reel groups complementary scenes and identifies camera, lens and exact role.", "A project note links audience confusion to missing spatial coverage and defines a new preproduction check."],
    ["Including every completed exercise regardless of relevance or quality.", "Using reflection to justify choices instead of testing whether they communicated."], [bfiLearning, adobeVideo]),
};
